### ISSUE TITLE
Preview (dry run) feature for services

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia#265]
Hello,

In previous versions, Onyxia had a feature that let the user get the Kubernetes contracts that would be deployed.
The API still has a `dryRun` parameter that can be used to get the contracts without deploying the service (see https://github.com/InseeFrLab/onyxia-api/blob/master/onyxia-model/src/main/java/fr/insee/onyxia/model/dto/CreateServiceDTO.java#L54).  

I suggest we bring back the preview button (could be an eye icon or something like that).  
We have to make sure the average user is not confused by this button. We can either hide it behind the beta-test flag or use some UX trick to make the user aware this is just a preview button.

**Comment by fcomte** [comment]
@olevitt still want this feature ?

**Comment by olevitt** [comment]
It may be useful but it's not top priority at all especially given we now have to corresponding helm command displayed to the user
