### ISSUE TITLE
message informatif quand `service.image.version` incorrect

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/onyxia#287]
J'avais cette url en service favori :

`https://datalab.sspcloud.fr/launcher/inseefrlab-helm-charts-datascience/rstudio?autoLaunch=true&onyxia.friendlyName=«utilitr-tester»&init.personalInit=«https%3A%2F%2Fraw.githubusercontent.com%2FInseeFrLab%2FutilitR%2Fmaster%2Fresources%2Finit_9juin.sh»&service.image.version=«inseefrlab%2Futilitr%3A0.7.0»`

Or le service.image.version `inseefrlab/utilitr:0.7.0` a été remplacée par `inseefrlab/utilitr:0.8.0`, ce qui cause ce méchant message d'erreur au lancement :

> There isn't an onyxia-api hosted at https://datalab.sspcloud.fr/api Check the ONYXIA_API_URL environnement variable you provided with docker run.

Détecter si l'image est inconnue et fournir un message d'erreur informatif à l'utilisateur ?

**Comment by garronej** [comment]
Salut Pierre-Yves.  
Merci pour le rapport et la suggestion.  
La rétrocompatibilité des configurations enregistrée est un problème que nous avons identifié.  
Nous ne savons pas comment le résoudre à ce jour. 😕  
Nous y réfléchissons.

**Comment by fcomte** [comment]
Hello,

Il y a deux points à améliorer : 
- Je pense que c'est tout à fait possible de contrôler ce genre de chose avant de tenter l'installation.
Le schema est connu de l'application : avant le lancement en autolaunch ou sans autolaunch on peut vérifier l'adéquation au schéma.

- Le fait de gerer les versions de charts ( ce qui est fait coté API depuis peu ) qui permettrait d'eviter les changements de schema entre la sauvegarde d'une configuration de service et son lancement plus tard

Meme si on fait le point 2 , il serait tjrs bon de controler le schema avant d'afficher le formulaire pour eviter d'avoir des crash de l'interface si le user demande un truc absurde vis à vis du schema.

Qu'en penses tu @garronej ?

**Comment by odysseu** [comment]
![image](https://github.com/InseeFrLab/onyxia/assets/55583423/2fcdd736-3780-4483-a0db-9e9a548e7172)
