### ISSUE TITLE
upgrade a chart

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia#352]
We can upgrade a chart.
![image](https://user-images.githubusercontent.com/48868412/189552187-5caa3edb-12ff-434b-9dc9-20514ca2c4c9.png)

There are two steps involved : 
- [ ] First is to saved the query string ( as we do for a saved config inside vault ) inside a specific values of the helm chart. onyxia.userDefinedValues.   
- [ ] In a second step we can create a button and linked it to the upgrade/install api calls. 

For that we need to save the fixed values somewhere (maybe in a custom values). 
Onyxia-web must fill all the automatic values then fixed values are apply ( fixed values overwrite automatic values )

**Comment by LoicMnz** [comment]
Hi @garronej,
With @alainds we have work on this issue. Can you review our PR?
