### ISSUE TITLE
console for the service tab

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia#360]
We have a console for minio and vault integration which help user to learn about CLI.
We can have the same idea for all helm operations.

- [x]  add a helm ls console when browsing running services. 
- [x] add a hel upgrade console when a chart is upgraded ( note : this feature is not yet done ) 
- [x] add a helm install console when manipulation is done over the laucher ( the switching to the running service after installing may be complexe to handle )

**Comment by garronej** [comment]
Love this feature.  
If anyone wants to takle it ping me so I can help you get started.
