### ISSUE TITLE
[Connexion button]

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia#447]
Add an option to disable this button (left one) if the button is really wanted.
Or just make it disapear at some could think this is a bug.

![image](https://user-images.githubusercontent.com/63847345/207136710-b6db50ed-7122-4ee3-a919-529b54db2b74.png)

**Comment by fcomte** [comment]
i agree i think we should remove it

**Comment by greg2451** [comment]
Can I take ? Would be interested to discover the codebase. I think I found what to change.

**Comment by garronej** [comment]
@greg2451 sure :)  

The thechnical documentation is here: https://docs.onyxia.sh/contributing/onyxia  (you'll need at least to run the commands from the "quick start")

**Comment by garronej** [comment]
@fcomte What is the problem with this button?  
I don't mind it being removed but I don't understand what's wrong with it.

**Comment by greg2451** [comment]
@garronej I suppose that it is the fact that there is two identical buttons on the same page (+ they are quite near)

It is not as disturbing on this view (which I obtained locally following [these instructions](https://docs.onyxia.sh/contributing/onyxia/quick_start))

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/51173502/207377002-0bc59a0b-da1a-429c-a2b0-2b0d76f86b8c.png">

Furthermore, when logged in, this button gracefully convert into a link to the docs, which is great UX

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/51173502/207377853-56639f5a-bbfb-4bb9-99ff-1be15dda8452.png">

Are you sur you want to fix ? Am i addressing the right issue.

Maybe an intermediary solution would be to hide the button when not logged, and keep the _New to datalab_ button for logged in state

**Comment by garronej** [comment]
Hi @greg2451,  

If you could suppress the button when the user isn't logged, it'll be great. :)   

Thank you for your involvement.
