### ISSUE TITLE
Wrong condition to disable the list of project  

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia#469]
For now, the condition to disable the list of project is to have only one project.
(This is because , in our implementation SSPCloud we have a personnal project and maybe no share project)

But there is some implementation where user have only one share project and no personnal project.
(A personnal project is a project without group)

In this case I think we must show the list of project.. 
It's strange to not see the name of project where we are working.

**Comment by garronej** [comment]
Ok, I must merge #430 first.
