### ISSUE TITLE
Move away from keycloak specific library

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia#496]
We currently use [keycloak-js](https://www.npmjs.com/package/keycloak-js) library for authentication.  
This library is (as far as I know) specific to keycloak and does not support other providers.  
Work on onyxia-api to switch to a provider-agnostic adapter is close to done (see https://github.com/InseeFrLab/onyxia-api/pull/202).  
We should do the same for onyxia-web

**Comment by garronej** [comment]
The job would consist in writing another adapter for this port:  
https://github.com/InseeFrLab/onyxia-web/blob/main/src/core/ports/OidcClient.ts

Here is this Keycloak adapter: https://github.com/InseeFrLab/onyxia-web/blob/main/src/core/adapters/keycloakOidcClient.ts
Here is the mock adapter: https://github.com/InseeFrLab/onyxia-web/blob/main/src/core/adapters/phonyOidcClient.ts
