### ISSUE TITLE
The 'minimize' button disappears when too many files are being uploaded in the 'My files' menu

### ISSUE THREAD

**Issue by odysseu** [InseeFrLab/onyxia#519]
When I upload several files using the `My Files` > `Upload file` button, the uploads stack in a list-kind-of window. When too many files are being uploaded, the `minimise` button of the list disappears under the navigator window like so : 

![image](https://user-images.githubusercontent.com/55583423/229738866-f41b55f7-c192-4fe1-83b4-ee51a2fcf675.png)

**Comment by garronej** [comment]
Thank you for the report.  
Indeed we need a max height and a `overflow: auto`

**Comment by garronej** [comment]
Fixed, will be relased in v8
