### ISSUE TITLE
S3 bucket synchronization

### ISSUE THREAD

**Issue by nashugame** [InseeFrLab/onyxia#530]
Facing an issue with synchronisation of uploaded data done via CLI/application with S3 interface of the Onyxia. Data is uploaded on S3, is accessible through CLI/application but is not viewable from my-files interface of the Onyxia.

**Comment by fcomte** [comment]
can you send us the error message when you browse file from onyxia-web ?
There is no synchronisation.. Onyxia-web just send S3 request to data storage so you should be able to see what's going wrong in network exchange

**Comment by nashugame** [comment]
There is no error as such. It's just that If I upload something on S3 bucket via program/CLI, the same content is not reflected on my-files UI interface of Onyxia. Though the content is there in S3 if I try to access it using program/CLI. 
![Screenshot from 2023-05-26 15-05-54](https://github.com/InseeFrLab/onyxia-web/assets/34041404/38fbde2c-f8ae-466b-af3e-fbc227a365eb)
![Screenshot from 2023-05-26 15-06-26](https://github.com/InseeFrLab/onyxia-web/assets/34041404/919b7b32-4bfb-4848-9704-5f5cdd44f939)

**Comment by garronej** [comment]
Hi @nashugame,  

The web UI dosen't suscribe to S3 events yet.  
Right now you have to hit the refresh button to see the changes.

**Comment by nashugame** [comment]
Hello @garronej ,
I had already tried the refresh button to see the changes, but it's not working. It's working only for the data uploaded via Onyxia UI not for the one done via CLI/program.

**Comment by garronej** [comment]
Is that so? And is you refresh the page?

**Comment by nashugame** [comment]
Yup, tried both refresh button as well as refreshing the webpage

**Comment by fcomte** [comment]
maybe a problem related to the other bug... maybe we doesn't not use region information in the web browser

**Comment by fcomte** [comment]
can you send us the S3 response to the OnyxiaWeb call to Amazon S3 service ? (the request who list the bucket)

**Comment by nashugame** [comment]
![Screenshot from 2023-05-26 19-09-59](https://github.com/InseeFrLab/onyxia-web/assets/34041404/3a39c108-752e-49b2-8c3c-8aa5a9f77274)

**Comment by fcomte** [comment]
how did you upload this file ? with UI ...
do you see it inside a jupyter or vscode ?

**Comment by nashugame** [comment]
Yup, uploaded using UI. Able to access the uploaded stuff inside jupyter/vscode using CLI but not the vice-versa.

**Comment by fcomte** [comment]
this is so strange .. I have no idea at the moment
