### ISSUE TITLE
S3 python code snippets not working

### ISSUE THREAD

**Issue by nashugame** [InseeFrLab/onyxia#531]
In python code snippet endpoint_url = 'https://'+'s3.{**region**}.amazonaws.com' need to have region as well to make it work.
![Screenshot from 2023-05-26 11-45-08](https://github.com/InseeFrLab/onyxia-web/assets/34041404/a24bc21c-9aef-4324-98f4-6dc1c578fe12)

**Comment by garronej** [comment]
I'm on it, thanks for reporting
