### ISSUE TITLE
vault engine path should be a parameter in region configuration

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia#534]
When the vault admin set a vault enable jwt by default it's jwt the name generated but the administrator could override the path when setting the jwt.

In this case onyxia ui try to reach https://vayltUrl/onyxia/v1/auth/jwt/login instead of https://vayltUrl/onyxia/v1/auth/overridePathByAdmin/login.

The proposition is to add a default region configuration value in vault section that allow the ui to reach the override endpoint.

**Comment by fcomte** [comment]
We should to do that fast

**Comment by fcomte** [comment]
onyxia-api is ready

**Comment by garronej** [comment]
Ok let's do it

**Comment by garronej** [comment]
Done in 2.20
