### ISSUE TITLE
Switching language make menu labels disappear

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia#537]
Steps to reproduce : 
- load onyxia  
- switch language (bottom dropdown menu)  

left menu labels will disappear and the UI will slowly resize  
Screenshot :  
![image](https://github.com/InseeFrLab/onyxia-web/assets/3159134/b34281f9-3e6c-4ad8-bd32-7cbee3de3725)

**Comment by garronej** [comment]
Ok that makes sence to me.  
I did a hack to prevent the previous bug that I couldn't reproduce.  
I was expecting this bug to occur.  

Thanks for reporting

**Comment by garronej** [comment]
Thank you for reporting
