### ISSUE TITLE
Double call on sts endpoint

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia#544]
When i click on launch of service card just after catalog of services in all services section.

![image](https://github.com/InseeFrLab/onyxia-web/assets/63847345/3846a812-f3d5-442b-9a00-e7a3bca4ec87)

I can see that there is multiple call on sts endpoint.

Minimize the number of generated temporary token by minio is quite important to minimize the overhead of the storage.

Probably a react problem with lifecycle component?

**Comment by garronej** [comment]
Great, thank you for reporting!

**Comment by fcomte** [comment]
fixed
