### ISSUE TITLE
Show user or group quotas in my account and its current consommation

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia#546]
the endpoint quota already exists and return the quota of the projet and the current consommation it could be shown to the user in an appropriate part in my account

**Comment by fcomte** [comment]
![image](https://github.com/InseeFrLab/onyxia/assets/48868412/a8336ff9-6905-48ac-a8ef-f236f5e05e89)

I think we should add a button to get quotas near delete. 
I think this information is not enough valuable to be always present on the screen

**Comment by odysseu** [comment]
I think what was meant is to show the current resourcequotas in the following window:
![image](https://github.com/InseeFrLab/onyxia/assets/55583423/8b956193-e746-46a6-b6e7-7991f80b8ff3)

**Comment by fcomte** [comment]
Kubernetes quotas are related to my services. So I think we should put this information on this component. 

My account page is a mix of personnal information and project related information. I think this component need a refactor.

**Comment by odysseu** [comment]
Was suggested later in https://github.com/InseeFrLab/onyxia/issues/696 and then done since https://github.com/InseeFrLab/onyxia/releases/tag/v8.9.0
