### ISSUE TITLE
My files shows empty bucket (but subfolder listing works fine)

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia#549]
Since latest minio upgrade (not sure which version, we upgraded from [RELEASE.2023-05-18T00-05-36Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-05-18T00-05-36Z) to [RELEASE.2023-06-16T02-41-06Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-06-16T02-41-06Z)), the user bucket listing returns an empty listing in response which leads to Onyxia displaying an empty bucket.  
Listing a subfolder works fine.  
Example : 
* https://minio.example.com/userid?delimiter=%2F&encoding-type=url&max-keys=1000&prefix=%2F  
```XML
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>userid</Name><Prefix>/</Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><EncodingType>url</EncodingType></ListBucketResult>
```  
* https://minio.example.com/userid?delimiter=%2F&encoding-type=url&max-keys=1000&prefix=mysubfolder%2F  
```XML
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>userid</Name><Prefix>mysubfolder/</Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><Contents><Key>mysubfolder/example</Key><LastModified>2022-02-10T16:59:12.426Z</LastModified><ETag>&#34;d2fcc1fac5b84b98132ca3036e9a949f&#34;</ETag><Size>15</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName>minio</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents><EncodingType>url</EncodingType></ListBucketResult>
```  

Currently unsure if that bug is attributable to Onyxia or MinIO (could not find any related issue on minIO / minIO-JS repositories) but we may have been doing something non-standard that is not supported anymore.

**Comment by garronej** [comment]
Fixed, deploying
