### ISSUE TITLE
Give the opportunity to add a communication message in the home page of onyxia

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia#556]
Maybe we could add the opportunity to add in the region configuration a string message that could be display on the home page of onyxia with the possibility for the user to delete the message.

Like gitlab message feature.

It could be helpful to give some maintenance information, or news.

**Comment by fcomte** [comment]
We had this functionnality before. This was provided by a simple env in onyxia-web. I guess we should do the same.
Is that easy @garronej ?

**Comment by garronej** [comment]
Trivial, I'll do it tonight

**Comment by garronej** [comment]
Shipped in 2.19.0

See [documentation](https://github.com/InseeFrLab/onyxia-web/blob/c012340e8235a99e6758b38e19e8cf413a50b374/.env#L41-L80).  

- [x]: Renders the message as a markdown text, it enables to feature links and to format the text.
- [x]: Enable, to specify the severity of the message, default is info. 
- [x]: i18n: The message is localizable.
- [x]: a11y: Screen reader read the message with the correct syntetization voice.
- [x]: Persistance: When the message is closed once it dosen't show on next reload, it's reset when the severity or the message is updated by the administrator.  

https://github.com/InseeFrLab/onyxia-web/assets/6702424/9067a95a-e5d9-4d35-b4a9-29cf9ce7dc60
