### ISSUE TITLE
S3 : provide a way to use an external s3 service with direct credentials

### ISSUE THREAD

**Issue by micedre** [InseeFrLab/onyxia#567]
I'd like to have a way for an user to use the `My Files` but with an external service. By exemple : user1 would use his own minio, user2 his own aws S3 bucket.

A way to do it could be by leveraging vault to store S3 credential by user (in the same way as git), an if s3 credential is provided, the the my file page is enabled with those credential.

Would it be possible to implement something like this ?

**Comment by fcomte** [comment]
Yes we already had this kind of idea with the ability to add "external sources". 
It's not easy to implement so you will not have it soon. 

The file browser is not the only usage of S3, there is also the injection of credentials while launching a service. We should state which credentials to inject ... external S3 or the temporary credentials of the main S3 configuration

**Comment by fcomte** [comment]
We are going to work on this feature now @garronej @micedre.

So in the future we should assume that : 
- there is or there is not a default S3 bucket for the project ( depending on the S3 configuration on the region )
- a user can 'per project' give other credentials and endpoints access to multiple other buckets ( or a first bucket if no default S3 bucket ). This information should be store in vault for the project (as password for services).
- the file browser should be able to browse all S3 data source
- a user should easily choose S3 sources when creating a service

**Comment by fcomte** [comment]
I guess this functionnality (adding data source) should be accessible in the "My file" section but we can discuss about the UX 

I guess in the region we should add an option to allow or not this feature ( a user adding his own S3 configuration ). For those that use onyxia as kubeapps there is no matter of S3.. ( no default S3 no feature to add it )

**Comment by alexisdondon** [comment]
We've discussed also this feature but from my understanding :
- the user add the s3 datasource per project then onyxia should persist it and at this time, the only choice from onyxia architecture is vault (and why not here as it is some credentials to store s3url, accesskey, secretkey and a name for the datasource).
    - the doc probably will have to say that having a vault is then a prerequisite to this feature?

To be really a full and healthy feature, this PR https://github.com/InseeFrLab/onyxia-web/issues/575 should be discussed to avoid onyxia project space to be a security leak to some s3 credentials.

**Comment by alexisdondon** [comment]
Then i ve made this issue that is, from my point of view, a prerequisite https://github.com/InseeFrLab/onyxia-web/issues/577

**Comment by fcomte** [comment]
- [ ] create a new web environment variable to totally remove the file explorer
- [ ] assume that by default a file explorer exist even if there is not S3 configuration in region
- [ ] create a new logic to assess file browser and futur data explorer : ( 1) oidc... 2 ) service account... 3) blank page specifying there is not data store available )
- [ ] create a new button to create an service account in this project ( assume only one service account ). This configuration must be store in vault.
- [ ] modify launcher injection

We can inject in the catalog launcher : 
- if allowed, personnal injection first
- if not , use service account
- no injection if nothing

**Comment by fcomte** [comment]
this is done in the next release
