### ISSUE TITLE
Cache for onboarding

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia#568]
Onyxia-web is saving inside vault if a project is onboarded or not. 
I think we should not save this information so long because if an administrator delete the namespace , then onboarding will not be called.

**Comment by garronej** [comment]
Ok good point.

**Comment by fcomte** [comment]
@garronej we should keep this information only on the session storage , not localstorage or vault.

**Comment by garronej** [comment]
Done in https://github.com/InseeFrLab/onyxia/commit/bf8de053c367b20f607f0dd74432702ba19e816a
