### ISSUE TITLE
Theming: custom assets

### ISSUE THREAD

**Issue by mmwinther** [InseeFrLab/onyxia#569]
In the interests of deploying Onyxia in contexts other than SSPCloud, it is highly desirable to be able to customize the branding of the Onyxia platform. I note that this is one of the advertised features of Onyxia so I assume this type of customization is desirable for the project.

In particular we would like to be able to customize and supply assets for the following areas circled with green:

![Screen Shot 2023-07-31 at 13 22 44](https://github.com/InseeFrLab/onyxia-web/assets/42948872/f4fc62f4-a7e3-48ef-9741-9248505fe65c)

**Comment by fcomte** [comment]
I agree

**Comment by garronej** [comment]
Done! https://docs.onyxia.sh/theme
