### ISSUE TITLE
Theming: customize home page text

### ISSUE THREAD

**Issue by mmwinther** [InseeFrLab/onyxia#571]
When deploying Onyxia in contexts outside SSPCloud, it is desirable to configure the welcome message and link shown to users when they arrive on the home page.

![Screen Shot 2023-08-01 at 12 41 05](https://github.com/InseeFrLab/onyxia-web/assets/42948872/614300d9-216a-4960-86d2-cfd7b7e728f0)

**Comment by garronej** [comment]
Ok!

**Comment by garronej** [comment]
Done! https://docs.onyxia.sh/theme
