### ISSUE TITLE
An interactive services should not allow the option to be shared

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia#578]
As interactive servnces trend is to be only a personal service we should not allow the checkbox that let the user choose if he want to share or not

**Comment by alexisdondon** [comment]
An option is two add 3 keys in the catalog if not specified all are false, if specified true it allow to choose where the catalog is visible and if the option shared the service is show or not.

By default disableSharing should be true for namespace interactif.

```
{
          "id": "aut",
          "name": "Services automation",
          "description": "Equipe datascience charts automation",
          "maintainer": "dg75-dsi-equipe-datascience@insee.fr",
          "location": "https://urltohelmcharts/",
          "status": "PROD",
          "type": "helm",
          "disallowUser" : "true"
          "disallowProject" : "true"
          "disallowSharing" : "true"
        }

```

**Comment by johnksv** [comment]
I think this would make sense.

One suggestion I have is to structure the json a bit more, instead of boolean values on "root". Maybe something like this: (please suggest better/other names or another structure)
```json
{
  "id": "aut",
  "name": "Services automation",
  "description": "Equipe datascience charts automation",
  "maintainer": "dg75-dsi-equipe-datascience@insee.fr",
  "location": "https://urltohelmcharts/",
  "status": "PROD",
  "type": "helm",
  "visible": {
    "user" : "true"
    "project" : "true"  
  }
  "allowSharing" : "true"
}
```

**Comment by olevitt** [comment]
I created a PR on this API. Feedback welcome, let me know if it's ok for you : https://github.com/InseeFrLab/onyxia-api/pull/269

**Comment by johnksv** [comment]
I belive this issue can be closed, as https://github.com/InseeFrLab/onyxia-api/pull/269 is merged, @olevitt

**Comment by garronej** [comment]
Great @johnksv, thank you for following up!
