### ISSUE TITLE
inject mode (light or dark) of Onyxia 

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia#581]
Onyxia knows the preference of users ! let's use it to configure IDE automatically !

We need a syntaxe to inject this user preference in "Onyxia values".

**Comment by garronej** [comment]
Yet another feature that we pretended we already had in the video:  
https://youtu.be/vpkgfgGxdMc?si=OP8faiOEVvO2KEZC&t=20  

I can inject in values no problem.  
How about `user.colorScheme: "light" | "dark"` or `user.darkMode: boolean` ?

**Comment by garronej** [comment]
Done in 2.29.  

`user.darkMode: boolean`
