### ISSUE TITLE
A hidden service should not be accessible from the search bar

### ISSUE THREAD

**Issue by ihiverlet** [InseeFrLab/onyxia#590]
When using the search bar, users can access services belonging to hidden catalogs. This should not happen. 

For example when searching 'vscode-python', users can launch a service named vscode-python-hidden which belongs to a hidden catalog. However, they should not be able to visualize it. 
![image](https://github.com/InseeFrLab/onyxia/assets/94982379/fcea0373-02a4-42f1-9935-1a7a36ad3e3d)

**Comment by garronej** [comment]
@ihiverlet, that's correct!
Thank you for bringing this to my attention.
I'm currently in the midst of a complete overhaul of our release pipeline, so I can't easily make a release at the moment. However, I'll address this issue as soon as I've finished with the ops work!

**Comment by garronej** [comment]
Thanks for reporting, it has been fixed 👍🏻
