### ISSUE TITLE
Bad banner positions and concise mode suggestion

### ISSUE THREAD

**Issue by odysseu** [InseeFrLab/onyxia#603]
couple things around banner and UI
- [ ] banner should be sticking to window side (same thing on its right side) (1)
- [ ] banner should not be over "Project" bit (2)
- [ ] Onyxia logo's bottom should probably not be this close to separator (3)

![banner_and_ui_issue_github](https://github.com/InseeFrLab/onyxia/assets/55583423/a4e0c30a-7c5b-40ec-8b68-92452dcb914f)

All-in-all I think it would be fortunate to have a "concise" mode where all spaces would be as small as possible, so the content in Onyxia is emphasized.

**Comment by garronej** [comment]
Hello @odysseu,  

Thanks for the report.  
As you can see there there's a lot going on on the project at the moment but I'll get to this ASAP.  
It's maybe the migration to https://github.com/garronej/screen-scaler that had some unintended side effect, I'll check this out.

**Comment by odysseu** [comment]
Hello,
No problem that is not a priority at all :)

**Comment by garronej** [comment]
<img width="493" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/f57cef08-1b96-4b41-b1f2-ce598610b9d1">

Fixed, I didn't introduce a param for making it small, the margin where to big to begin with.  

Thanks for reporting!
