### ISSUE TITLE
Weird quote marks around onyxia version at bottom right of UI

### ISSUE THREAD

**Issue by odysseu** [InseeFrLab/onyxia#606]
Hi,
| comment | screenshot |
| --- | --- |
| The following screenshot highlights an odd way the onyxia version is displayed in the bottom right corner of the UI. <br /> <br />  | ![image](https://github.com/InseeFrLab/onyxia/assets/55583423/f2e10b93-b3d0-4e72-8e06-9038b846dccb) |
| what's more is the link it hides is `https://github.com/InseeFrLab/onyxia/tree/"4.1.2"/helm-chartt`, where `"` is `%22` and therefore sends to the folowwing github page | ![image](https://github.com/InseeFrLab/onyxia/assets/55583423/a9ef0c8b-697c-4eba-b2ef-0e4162e45f68) |

**Comment by garronej** [comment]
Hi @odysseu,  
Happy to see you're closely following Onyxia devlopement!  
I introduced this bug tomorrow night and this morning we had a meeting with scikit learn but I'm fixing this and the banner issue todat!   

As always, thanks for reporting!

**Comment by odysseu** [comment]
Thanks for the quick reaction, too. Thanks in advance!
🏎️

**Comment by olevitt** [comment]
Fixed by e332880
