### ISSUE TITLE
Authentication : issue with firefox

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia#612]
Since the latest version (probably `v4.2.4`), most likely due to the change keycloak => oidc, authentication seems to fail at first try when on firefox (tested on latest firefox on windows and linux). Authentication works but after being redirected to Onyxia the user is not logged in. 
Retrying authentication multiple times seem to work.

No issue on chrome

**Comment by garronej** [comment]
Sneaky bug.
