### ISSUE TITLE
Issue on Firefox - "My Files" tab

### ISSUE THREAD

**Issue by slim-mercator** [InseeFrLab/onyxia#615]
Hi,

We can't load the "My Files" tab running the latest version of Firefox (v. 118.0.1) on macOs. It works well on Linux (but versions of firefox appears to be different depend on the platform).
Our onyxia instance is running the 4.2.2, this is not the latest version but we are close. So tell me if this problem has been fixed in the meantime. 
Because we have access to your ssp cloud instance of the datalab, we also tried on it (v. 4.4.1 at this time) and it doesn't work either.

Let us know.

**Comment by garronej** [comment]
Thank you for reporting!  
I'ts fixed in the last v4 version and in v5
