### ISSUE TITLE
Helm-chart: Onyxia-api and web use same service account (SA) if SA is provided via name

### ISSUE THREAD

**Issue by johnksv** [InseeFrLab/onyxia#616]
Hi!
In the helm chart it is possible to "bring you own" service account by setting `create` to false and providing a name, i.e.:
```yaml
serviceAccount:
  create: false
  name: my-service-account
```

Onyxia-api and onyxia-web will use the same service account when this is the case, as can be seen here:
onyxia-api: https://github.com/InseeFrLab/onyxia/blob/b5593567904f8a8c7bc31e6852e88a6e12cb30b4/helm-chart/templates/_helpers.tpl#L114
and here https://github.com/InseeFrLab/onyxia/blob/b5593567904f8a8c7bc31e6852e88a6e12cb30b4/helm-chart/templates/_helpers.tpl#L122

This is a big security issue, as the two apps need fundamentally different permissions in the cluster in order to operate. Onyxia web is in other words given far to many privileges when this approach is used.

**Suggested solution**
I take the liberty to make a suggestion for fix, but please take this as a starting point for further discussion:
Remove `serviceAccount` from root level of helm chart, and instead create a new field both for api and web (i.e. `web.serviceAccount` and (`api.serviceAccount`). 

Short pros/cons:
Cons: Breaking change -> new major
Pros: More explicit which service account is used, and which permissions which follows

**Comment by fcomte** [comment]
We need to fix that obviously and I agree on your proposal

**Comment by johnksv** [comment]
Closing issue, as this was fixed in #621
