### ISSUE TITLE
[Feature Request] Disable support for specific languages

### ISSUE THREAD

**Issue by Andilun** [InseeFrLab/onyxia#624]
### Issue
To maintain SSB's ability to make the necessary customizations and ensure that our fork remains closely aligned with the main Onyxia repository, we would like the ability to disable support for specific languages based on configuration.

### Feature description
A configuration option, such as `REACT_APP_DISABLE_LANGUAGES=zh-CN,fi,it`, that allows us to selectively disable support for a subset of languages. This feature will enhance the flexibility and maintainability of customized Onyxia deployments while ensuring the preservation of default language support for others.

**Comment by johnksv** [comment]
To turn it upside down: Would it be better to instead specify which languages should be enabled? `REACT_APP_ENABLED_LANGUAGES` ?

**Comment by Andilun** [comment]
> To turn it upside down: Would it be better to instead specify which languages should be enabled? `REACT_APP_ENABLED_LANGUAGES` ?

Good suggestion, that would be a better approach!

**Comment by fcomte** [comment]
With an evolving list of languages, enabling them seem more consistant and less time consuming for administrators.

**Comment by Andilun** [comment]
> With an evolving list of languages, enabling them seem more consistant and less time consuming for administrators.

Good point, I agree.

**Comment by garronej** [comment]
Okay guys! 👍🏻

**Comment by garronej** [comment]
Surprisingly, this was harder that I anticipated, anyway it's done :)  

https://github.com/InseeFrLab/onyxia/blob/3f3aa0aa989787601d179d9019219a91dacfc1f5/web/.env#L203-L210
