### ISSUE TITLE
Add gouvernance files in Onyxia

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia#625]
We should add : 

- [ ] DCO.md
- [ ] CONTRIBUTING.md
- [ ] CODE_OF_CONDUCT.md
- [ ] ROADMAP.md
- [ ] MAINTAINERS.md
- [ ] SECURITY.md

**Comment by johnksv** [comment]
Maybe also `SECURITY.md`?

**Comment by olevitt** [comment]
Closed by #627
