### ISSUE TITLE
Injection darkmode not working

### ISSUE THREAD

**Issue by ihiverlet** [InseeFrLab/onyxia#628]
I use x-onyxia:{
          "overwriteDefaultWith": "{{user.darkMode}}"
        }
It seems to always send true to the api. 
Can be tested here and checked via the put request : https://datalab.sspcloud.fr/launcher/inseefrlab-helm-charts-dev/vscode-python-darkmode6bis?autoLaunch=false

**Comment by garronej** [comment]
Oh! Is that so?! 
Applogies!

**Comment by garronej** [comment]
It's fixed,  
Thanks for reporting.  

The app should have been resilient to this but note that the mustache syntax (`{{}}`) is to be used only for concatenating strings.  

```diff
    "userPreferences":{
      "description": "User Preferences",
      "type": "object",
      "properties": {
        "darkMode": {
          "type": "boolean",
          "description": "dark mode is or is not enabled",
          "default": false,
-         "x-form": {
-          "hidden": true,
-           "value": "{{user.darkMode}}"
-         },
          "x-onyxia": {
            "hidden": true,
-            "overwriteDefaultWith": "{{user.darkMode}}"
+            "overwriteDefaultWith": "user.darkMode"
          }
        }
```  

https://docs.onyxia.sh/catalog-of-services

<img width="860" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/bf4bbc9d-5ca6-4559-83c8-2491f0210f4e">

Anyway thank you very much for reporting this. It's very good that this bug has been spoted! 💯

**Comment by ihiverlet** [comment]
Thanks for pointing this out !
