### ISSUE TITLE
Hide passwords and token in My account's tabs

### ISSUE THREAD

**Issue by odysseu** [InseeFrLab/onyxia#634]
Hi,
could more variables in the _My account_ tab of onyxia be rendered as password ? This would be useful when sharing screen.

For instance the ["personal token"](https://github.com/InseeFrLab/onyxia/blob/main/web/src/ui/pages/account/tabs/AccountIntegrationsTab.tsx#L128C34-L128C50) has the [`isSensitiveInformation={true}` configuration](https://github.com/InseeFrLab/onyxia/blob/main/web/src/ui/pages/account/tabs/AccountIntegrationsTab.tsx#L148) but it might also be a good choice to enable it on
- ["oidcAccessToken"](https://github.com/InseeFrLab/onyxia/blob/main/web/src/ui/pages/account/tabs/AccountKubernetesTab.tsx#L88)
- ["AWS_SESSION_TOKEN"](https://github.com/InseeFrLab/onyxia/blob/main/web/src/ui/pages/account/tabs/AccountStorageTab.tsx#L127)
- ["AWS_SECRET_ACCESS_KEY"](https://github.com/InseeFrLab/onyxia/blob/main/web/src/ui/pages/account/tabs/AccountStorageTab.tsx#L126)
- ["vaultToken"](https://github.com/InseeFrLab/onyxia/blob/main/web/src/ui/pages/account/tabs/AccountVaultTab.tsx#L90C28-L90C40)

**Comment by odysseu** [comment]
A PR is possible but you will be much faster on this one

**Comment by trygu** [comment]
Still shows secrets in plain-text in the code examples though..

**Comment by odysseu** [comment]
Maybe there could be
- a "show"/"hide" button for the code example as well...

Or 

- a dummy text that matches the "is shown" of the values. The code at first is a dummy code, and when a button "show/hide" is checked then the values and the code are the real ones.. ?

**Comment by odysseu** [comment]
Good enough for now; 

Maybe there could still be

- a "show"/"hide" button for the code examples as well...

Or

- a dummy text that matches the "is shown" of the values. The code at first is a dummy code, and when a button "show/hide" is checked then the values and the code are the real ones.. ?
