### ISSUE TITLE
Helm chart libraries are shown in Service Catalog

### ISSUE THREAD

**Issue by johnksv** [InseeFrLab/onyxia#642]
Hi! Just noticed that helm charts of `type: "library"` is displayed in the launcher catalog. Here from ssp cloud ( see library chart in bottom right corner):
![image](https://github.com/InseeFrLab/onyxia/assets/10381866/fc8bb9e7-a5d1-4d79-a718-10c39943287d)

I have not pinpointed the change that caused this, but may be related to the refactoring regarding versioning?

**Comment by garronej** [comment]
Ah yes, I see. 
Let me fix this just now!

**Comment by garronej** [comment]
Fixed!

**Comment by johnksv** [comment]
Hi, thanks for the quick fix, @garronej !
One suggestion on our implementation: P.t. you filtered based on name. I think it would be better to use the `type` field (which is either `library` or `application`) to decide whenever or not to show the package. I can see that this requires some changes of the type defined here https://github.com/InseeFrLab/onyxia/blob/main/web/src/core/adapters/onyxiaApi/default.ts#L365C36-L365C36 , but other than that it might be a reasonable approach. What do you think?

I'll add a picture of the response from api `/public/catalogs` so it can be easier to resonate around my suggestion:
<img width="678" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/10381866/3dc945a7-ddf2-47ab-9a82-11260b7a8c18">

**Comment by fcomte** [comment]
Yes this the good way to filter out

**Comment by garronej** [comment]
Yes! Good catch, I implemented a filter instead!
