### ISSUE TITLE
Revamping Account and Project Settings

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia#653]
This proposal outlines a restructuring plan for the 'My Account' section, leading to a more organized and user-centric interface. The key change involves creating two separate sections:

1. An independent 'My Account' area, which will function independently of any selected project
2. A 'My project' area, which will contain information about the selected project.

Here are the requested change for 'My account' : 
- [x] account infos : move password for services to the project section
- [x] account infos : totally remove IP adress.
- [x] account infos : check what happens if oidc is not keycloak. Just wondering if we handle the case.
- [ ] external services :  switch the name of this section to "git configuration"
- [ ] external services : remove kaggle, we don't care of that, there is no use case and no injection for this value.
- [ ] external services : add a git store type like github or gitlab and populate it with the default one from the region
- [x] external services : add a git store url and populate it with the default one from the region
- [x] connect to storage : we keep this configuration but this should only be tokens not scoped in a project

Here are the change for 'My project' : 
- [x] security infos : creation of a "security infos" tab
- [x] security infos : add the password for service (removed from account infos)
- [x] data sources : creation of a "data sources" tab, this section is empty by default
- [x] data sources : add a button to create a data source.
- [x] data sources : select type of the data source : in a first iteration there will be two type of source : internal S3 and external S3. 
- [x] data sources external S3 : allow registering this 5 parameters + 1 parameter for bucket name.
![image](https://github.com/InseeFrLab/onyxia/assets/48868412/3e7181ff-9281-46d7-b254-11aa90c0d699)
- [ ] data sources internal S3 : allow registering a service account for a the default storage space of a project ( 3 editable parameters, 3 read only parameters ) 

An external datasource can be used in Onyxia if this is allowed in the region configuration (https://github.com/InseeFrLab/onyxia-api/issues/301). 
Based on external storage S3 configuration we can use the file browser and data explorer. We can also make injection in the launcher.

An internal S3 source is mainly a service account in the context of a project. If there is no S3 configuration , this datasource should be hidden. We don't need to use those credentials to launch the file explorer or dataexplorer ( personnal tokens are better for this purpose ). But we should inject thoses token as a fall back for the S3 injection ( if personnal token injection are disallow in groups )

PS : on labelling "good first issue" , adding datasource on this issue is complexe but everything else is very ease

**Comment by garronej** [comment]
> check what happens if oidc is not keycloak. Just wondering if we handle the case.  

Just not displaying the link:  https://github.com/InseeFrLab/onyxia/blob/27bb37690b9eb30fd17a8d569e57f58dae7996ef/web/src/core/usecases/userAccountManagement.ts#L89-L103

**Comment by ddecrulle** [comment]
> if (!new URL(issuerUri).pathname.match(/^\/(?:auth\/)?realms\/.*$/)) {

The current pattern for checking the issuer URI may not be suitable anymore in Keycloak 22, as the default issuer no longer includes '/auth' by default.

**Comment by garronej** [comment]
@ddecrulle @fcomte I know, this is why there is a `?`, `(auth\/)?` means "optionally a auth/ prefix"
