### ISSUE TITLE
Ability to launch "functions" or "processes"

### ISSUE THREAD

**Issue by qgau** [InseeFrLab/onyxia#660]
Hi there!

We would like let our users use the Onyxia datalab to launch time-limited "functions" or "processes", with inputs, generating output data, without UI.

We think Onyxia itself is well fitted for that because:
- the "functions" or "processes" are container-based computations
- at launch time, they require configurations similar to the Onyxia services (infra/resources, along with the process inputs and the output target location)
- the UX we have in mind is almost the same as the one for the services, meaning we want to expose a catalog of "processes", 
let the user launch them, and monitor their executions in a "My processes" section

So far we have been able to conceptualize these "processes" by creating a chart repository and adding a tab in the service catalog pointing to it.
In this repo, the chart are defined based on kubernetes jobs instead of deployment or statefulset like in other onyxia chart repositories.
When the job is done, the user can find the process output data under "My files" (by default).
We have been able to validate this with our user community. So now, we would like to improve the UX around these processes.

This implies:
1. As said above, being able to add "Process catalog" and "My jobs" (or "My processes" sections (on the left bar, below "Service catalog" and "My services".
2. Having API endpoints for processes (equivalent to the ones for services, but named "processes" instead.
3. Being able to tweak the tiles "in progress" to monitor the job, to be able to:
  a. indicate since when the job is over
  b. indicate if the job is in error (that point actually also apply for the services. If the underlying pod is in error, the user is not aware of it, right?)
  c. show a "View output data" button once the job is over, pointing the "My files" section with the right path (with a super-integration with the data explorer in the future, hopefully :-))

Here is a screenshot to illustrate point 3:
![ScreenShot](https://github.com/InseeFrLab/onyxia/assets/45388569/a0483339-95a8-4843-864f-9f222c4f8ae3)

We think these points could be tackled independently, especially 1 and 2 on one hand (we tried to express in issue #658) , and 3 on the other.

I tried to explain the rationale behind these "processes" in discussion #611, but to express it in a simple use-case, our users want to share pre and post data treatments (for example). 

To go on, we mainly would like to know your thought about it, if you are interesting in adding this to Onyxia (for us it makes sense, as it really to manipulate data around, so a "datalab" seems the perfect place, but maybe not for you).
If you are interested, do you think this should be optional?
If you are not interested, do you think a plugin mechanism could be added so that we won't have to fork Onyxia and struggle with maintenance.
If you are really not interested, no problem, we will fork and maintain to keep close to the root project :-)

About the naming ("functions", "processes", "jobs" or else), if it make sense to you to have this feature, but not to call it "processes", is it possible to make it customizable? Our community nomenclature for that is "process" for the declaration/definition, and "job" for the actual instances/runs (using only "process" everywhere for simplication is fine though).

Finally, we can gladly help with the implementation, by looking at the code, we feel like we can do it, but we want to stick to your design decisions and code style.

I hope our request is clear enough.
Thank you one more time for the awsome job on developing this platform!

**Comment by fcomte** [comment]
Some of Onyxia Instance have already done some helm chart containing cronjob. Enriching the onyxia-web with dedicated UX to handle job is something interesting. I agree with you. 

Maybe this issue should be describe in a discussion but we can also keep the discussion here

https://github.com/InseeFrLab/onyxia/issues/658 is more generalist and not focus on jobs... so I don't really understand your proposal. separation service versus jobs or separate experience on any catalogs

**Comment by qgau** [comment]
Hello, thank you for your feedback,

Never mind the link with #658, it was just a proposal of a common technical solution. 
Let's first agree on how the UX can handle such jobs.

Please note that we also have a need for  a cronjob interface, but going step-by-step, what we want is first the ability for a user to search, launch, monitor, pause or stop on-demand jobs from the datalab UI, while adding new process to the catalog will be done via PullRequests on the helm chart repositories (exactly like self-services).

How can we help to start the development? Do you need more specification or description of the need? Or a UI mock-up?

**Comment by fcomte** [comment]
Hello,
I apologize for the delayed response, i woush you an happy new year.

The challenge we're facing is developing software that is both effective and meaningful in a vast ecosystem. This is not an easy task. Although the feature you've suggested would be fantastic, I'm uncertain about its feasibility in Onyxia given its complexity. 

In the Onyxia datalab environment, there are alternatives like Argo Workflow that also offer valuable functionalities. Particularly, when you're working with frameworks such as Metaflow, you have the ability to create Argo workflow templates , in an effective way.

This leads us to some key questions:
- Should we design our own job abstraction layer with maybe a dedicated api to handle that ?
=> this choice would have an impact on our mindset : We aim to maintain high transparency in Onyxia, and ensuring reversibility is a key priority for us.
- Alternatively, should we adopt an existing solution, like Argo's workflow templates or cron jobs?

**Comment by Eldrile** [comment]
Hello,
Thanks for the answer, we are only just coming back to it.
I have taken a look at metaflow and argo workflow, and while they look great they don't really fit our need.
At the time being we will try and make something work by forking, hopefully if we do it right we might propose you a contribution at a later date ! (This depends if we manage to create something generic enough to be interesting for you)
Cheers !

**Comment by garronej** [comment]
@Eldrile let me know if you want an introduction to the codebase

**Comment by Eldrile** [comment]
@garronej Thank you very much , that would be great, the whole team in fact is interested, when is that possible for you?
Do you want to discuss it in slack?

**Comment by garronej** [comment]
@Eldrile Actually I just migrated to Vite so if you want I'm available right now.

**Comment by Eldrile** [comment]
@garronej if its not too much of a problem, would it be possible next week? Today we are in a code session with one of our partner.

**Comment by garronej** [comment]
Sure no problem. Hit me up on slack when you're available!
