### ISSUE TITLE
use `.tar.gz` instead of `.zip`

### ISSUE THREAD

**Issue by odysseu** [InseeFrLab/onyxia#669]
As `tar.gz` is more natural in unix OS

**Comment by garronej** [comment]
Hi @odysseu,  

I understand where this is comming from, it's indeed true that it's more natural on Unix platfom tu create .tar.gz however .zip is a more cross platform friendly format and I'd like to avoid complexifying the Docker image any more than it currently is.  

https://github.com/InseeFrLab/onyxia/blob/e8172b5519c29dc71eb80b38c3cfac6da077bf32/web/Dockerfile#L35-L38  

Thanks for the feedback anyway.

**Comment by odysseu** [comment]
Sure, that was more for a discussion than an actual issue.

And this way if someone suggests the same change one can see that we thought it through 😃
