### ISSUE TITLE
Snippets of code are available on user action but absent otherwise

### ISSUE THREAD

**Issue by Eldrile** [InseeFrLab/onyxia#673]
In "My Files", the code snippet only appears after the user has done an action, it is very interesting for transparency and to inform the user of the code used behind the interface. 
As a user I would like to have access to the different exiting code snippet without having to do the action each time I need the code, in order to have some ready code examples.
Maybe another color could be used for the default available action to differentiate with the actions produced by the user.

**Comment by fcomte** [comment]
I think Onyxia can't handle this. It will be too complex in this component : 

![image](https://github.com/InseeFrLab/onyxia/assets/48868412/3531caa4-7fbf-4b0e-9a82-7485c359fdee)

My feeling is that we can't manage a knowledge base directly in this web app.
