### ISSUE TITLE
Intuitive scrolling in service configuration

### ISSUE THREAD

**Issue by qgau** [InseeFrLab/onyxia#676]
Hello,

Would it be possible to make the scrolling over a service configuration bar more intuitive, especially with touchpad?
For now one can scroll accross tabs with top-bottom, is it possible to make it left-right?

![image](https://github.com/InseeFrLab/onyxia/assets/45388569/df861801-b7ec-451e-a047-1d573e7c1732)

What do you think?

**Comment by fcomte** [comment]
I am ok with the idea, i let @garronej tell us if he is ok too.

**Comment by garronej** [comment]
Done, brought to you by chatGPT https://chat.openai.com/share/855379e3-f73c-424d-936b-0e3e1d0763e7  

Could be refined though, the scroll is a bit lagish, would probably work beter if we increaced the delta.

**Comment by qgau** [comment]
@garronej you rock
