### ISSUE TITLE
API return error when launching second Mongodb

### ISSUE THREAD

**Issue by Eldrile** [InseeFrLab/onyxia#684]
While testing functionalities in the datalab I encountered this API error. When a mongodb service is already launched and the user try to launch a second one,  an error pop up appears : Onyxia API Error PUT /api/my-lab/app Response: 500.

I am not sur if two mongodb running at the same time is necessary but if this is forbidden by the API, maybe the interface shouldn't allow it?

**Comment by fcomte** [comment]
It's not so easy because there is no concept of "this app can be only be started one time"... Behind the scene, the helm chart of mongo was done like that. 

We should have better handling of error message.

https://github.com/InseeFrLab/onyxia-api/issues/347
