### ISSUE TITLE
GOVERNANCE.md contains leftovers from the initial template file

### ISSUE THREAD

**Issue by bzg** [InseeFrLab/onyxia#685]
E.g. https://github.com/InseeFrLab/onyxia/blob/main/GOVERNANCE.md#list-of-maintainers explains what should be in the `Maintainers.md` file: this part of GOVERNANCE.md should be cleaned up.

**Comment by fcomte** [comment]
I write that to explain that on each repository on the onyxia ecosystem , a list of mainteners must be created with the template format given in this gouvernance file. Every governance reader can then understand where to find the reference of mainteners.

**Comment by bzg** [comment]
Ah, I see.  The sentence "For each repository" is ambiguous, because it is not clear what "repository" refers to: perhaps a phrase after the heading "Repository Maintainers" could explain that this section is about maintenance of the repositories listed above, in the "Onyxia's Repository Structure" section. WDYT?

**Comment by bzg** [comment]
Any further input on my suggestion?

**Comment by garronej** [comment]
Thanks for the update, I'll address this
