### ISSUE TITLE
Hide or document the _Change account information_ in the _My Account_ menu

### ISSUE THREAD

**Issue by odysseu** [InseeFrLab/onyxia#688]
As shown in the following screenshot, some onyxia instances might depend on a out-of-hand OIDC where passwords can't be changed. What's more, the link you point to is not the same in every OIDC instance; 

![image](https://github.com/InseeFrLab/onyxia/assets/55583423/9684ad0e-db50-497b-bcbe-e58f17140dc5)

A solution could be either :

- change the link to which the _Change password_ button send the user to.

or

- add an option to disable or to display an informative message.

**Comment by garronej** [comment]
Hey @odysseu,  

This link is only displayed if the idientity provider is an instance of Keycloak.  

We figure out if it's an instance of keycloak by inferring it from the issuer uri.  

See: https://github.com/InseeFrLab/onyxia/issues/653#issuecomment-1806952759

**Comment by micedre** [comment]
If I may, even if we use keycloak, our users can't change their password on the account page.

I agree there should be a switch to disable this link entirely (or replace it with another).

**Comment by fcomte** [comment]
this is fixed
