### ISSUE TITLE
Error with data explorer on csv file

### ISSUE THREAD

**Issue by micedre** [InseeFrLab/onyxia#692]
Hi,

On my instance, when using data explorer on a csv file, I got the following error : 

![image](https://github.com/InseeFrLab/onyxia/assets/243027/01fc7e51-99a2-4fbc-83c0-d372ff118351)

A simple example to reproduce is attached : 
[id.csv](https://github.com/InseeFrLab/onyxia/files/13596286/id.csv)

(Same error on the sspcloud platform)

**Comment by fcomte** [comment]
it's solved in a recent version
