### ISSUE TITLE
Data explorer cannot serialize bigint

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/onyxia#694]
Hi !

Thanks a lot for the wonderful file explorer feature ! This can be a game changer for the dissemination of onyxia in teams where there are people less experts in programming. 

I wanted to test that with a parquet file I produced using Python. File is stored on Minio but also available using https link (which I will use for examples).

When I want to read this parquet via file explorer, I get the following error

![image](https://github.com/InseeFrLab/onyxia/assets/33896139/603acec9-515f-4243-a3a1-f386493116cc)

You can reproduce using this [link](https://datalab.sspcloud.fr/data-explorer?source=https%3A%2F%2Fminio.lab.sspcloud.fr%2Fprojet-funathon%2F2023%2Fsujet4%2Fdiffusion%2Fopenfood.parquet&rowsPerPage=25&page=1&columnWidths=%7B%7D&columnVisibility=%7B%7D).

Reading the same parquet file works with duckdb WASM version embarked by observable, you can find an example [here](https://observablehq.com/d/3397a6d1a12ae641). 

It looks like this `bigint` serialization issue happens a lot with parquet files written with Python, this is not the first time I encounter it.

**Comment by fcomte** [comment]
yes we already saw it , we will fix soon

**Comment by garronej** [comment]
Yes as @fcomte said it has been identified and will be fixed very soon!

**Comment by garronej** [comment]
Sorry it took me so long.
