### ISSUE TITLE
Substitution with field overwriteDefaultWith from x-onyxia should support other types than string

### ISSUE THREAD

**Issue by johnksv** [InseeFrLab/onyxia#702]
**Background**:
P.t. overwriteDefaultWith is expected to be a string which onyxia-web than [substitutes with a value from xOnyxiaContext](https://github.com/InseeFrLab/onyxia/blob/main/web/src/core/adapters/onyxiaApi/default.ts#L630).
The value from xOnyxiaContext can be a arbitrary type (string, array, object, etc). 

**Problem**
This mean the xOnyxiaContext must hold the whole value that should be substituted. This can not be done for every value, by the introduction of custom values, but is not ideal, since one in the chart maybe want have some hardcoded values. E.g. an array where only a subset of the elements are to be substituted:
```json
"x-onyxia": {
    "overwriteDefaultWith": [
        "{{value-that-should-be-subtituted-by-onyxia-web}}",
        "a hardcoded value",
        "some other hardcoded value",
        "{{region.oauth2.clientId}}"
    ]
}
```
There may be scenarios where overwriteDefaultWith might be an object.

**Suggested solution:**
Implement support for `overwriteDefaultWith` being of type string, array or object.

Don't know if this make sense, but wanted to raise the issue such that it can be discussed nonetheless.

**Comment by garronej** [comment]
Hi @johnksv,  

Thanks for bringing this to our attention, I have to take some time to understand in detail what you are saying but right off the gate I thinks there might be a missunderstanding on how the overwriteDefaultWith behave.  

The mustach syntax is **not** de preferred way to use this parameter. It just provide a way ton concatenate strings:  

<img width="899" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/5c574601-bba0-463d-9c75-43dada50f23b">

However the `overwriteDefaultWith` is suppose to reference directly a value from the XOnyxia context. This value can be of any type, string, number, object.  

<img width="618" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/af05430b-769b-4a49-b3e2-e1153bc4ba34">

Ref: https://docs.onyxia.sh/catalog-of-services

Let me know if it solve your issue or if it still need our attention.  

Best.

**Comment by johnksv** [comment]
Sorry if the suggested behavior did not come across clear enough. I'll try again:

To be more specific. The use case is that the type in the helm chart is defined as type array, but we only want a couple of the elements to be overwritten by onyxia.
E.g.:

```json
"hosts": {
    "type": "array",
    "description": "Array of hosts allowed to be accessed from your service",
    "default": [],
    "x-onyxia": {
        "hidden": true
        "overwriteDefaultWith": [
            "<field injected by onyxia-api>",
            "packagemanager.rstudio.com",
            "rspm-sync.rstudio.com",
            …
        ]
    }
}
```

Does that make sense?
If it were to be implemented it could probably look something like this (just pseudo-code for use case above, where type is array): https://github.com/InseeFrLab/onyxia/compare/main...statisticsnorway:onyxia:overwrite-default-array-support

I do not know if it makes sense to implement this kind of logic into onyxia-web though, as this can be solved by other approaches (in the helm chart itself, by using customValues, or other).
Feel free to close this issue in that case 😊 
If it make sense I can probably contribute the functionality

**Comment by garronej** [comment]
Ok gotcha, that makes perfect sense, it's a nice addition.  

A new version incorporating the requested changes is being published by the CI workflow.   

I did some refactoring (to many nested indentation) but the relevent part are here:  

- Doc: https://github.com/InseeFrLab/onyxia/blob/644f3fe88f683f5883d8fa8580b7ef4badb8c376/web/src/core/ports/OnyxiaApi/XOnyxia.ts#L9-L25  

- Code: https://github.com/InseeFrLab/onyxia/blob/644f3fe88f683f5883d8fa8580b7ef4badb8c376/web/src/core/adapters/onyxiaApi/utils/injectXOnyxiaContextInValuesSchemaJson.ts#L90-L162  

You can now write:  

```json
"x-onyxia": {
    "overwriteDefaultWith": [
        "a hardcoded value",
        "some other hardcoded value",
        "{{region.oauth2.clientId}}"
    ]
}
```
And expect `{{region.oauth2.clientId}}` to be substituted by onyxia.  

I did a little change in logic to make this possible. Now, if you have a string that start by {{ and ends by }} it means that the value referenced will be replaced as is (unlike before where it was serialized).  

Hope it works for you.
