### ISSUE TITLE
data explorer crashes with geoparquet

### ISSUE THREAD

**Issue by ericemc3** [InseeFrLab/onyxia#713]
For ex, with this file:
`https://static.data.gouv.fr/resources/irve-formt-geoparquet-20231222/20231223-185529/irve-20231222-geo.parquet`
If it's not on loading, the problem occurs with horizontal scrolling. I guess the issue originates in the rendering of the geometry field.

**Comment by fcomte** [comment]
This is right ! We will try to fix that soon. At least to screen the same as the web shell  :
![image](https://github.com/InseeFrLab/onyxia/assets/48868412/19a80ad0-7ff6-48f3-92a8-162b6c8353fa)

**Comment by garronej** [comment]
@ericemc3 thanks for reporting! It's fixed in 8.0.2

**Comment by ericemc3** [comment]
Thank you for the fix!
