### ISSUE TITLE
Service persisted configuration by URL

### ISSUE THREAD

**Issue by NicoLaval** [InseeFrLab/onyxia#732]
Hi,

Few versions ago we were able to save our service configuration copying URL.
When I try to configure a PySpark service, spark configuration is not filled in URL.

Example:
https://datalab.sspcloud.fr/launcher/ide/jupyter-pyspark?version=1.33.1&autoLaunch=false&onyxia.share=true&service.image.pullPolicy=%C2%ABAlways%C2%BB&service.image.custom.version=%C2%ABinseefrlab%2Ftrevas-

Even if I clean the spark config.

**Comment by NicoLaval** [comment]
Looks to be deeper:
- got to spark tab, clean, add a single property
- navigate to an other tab
- come back to spark tab
- default config is filled

**Comment by fcomte** [comment]
hello

Spark config is an object not a boolean or a string.
I guess this why it's buggy.
@garronej ?

**Comment by garronej** [comment]
I'm looking into it

**Comment by garronej** [comment]
@NicoLaval yes, ther's a bug big time, I'm fixing it, thank you for reporting.

**Comment by garronej** [comment]
Fixed

**Comment by NicoLaval** [comment]
Great, thank you for your quickness.
