### ISSUE TITLE
two bugs in 8.1.5 related to data explorer

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia#733]
Firstly, If user as not connected , https links are not working anymore : 

![image](https://github.com/InseeFrLab/onyxia/assets/48868412/73e377b5-a7b3-4d78-8d7b-bb1fc4f44190)

Secondly , download link for S3 are not working anymore : 

![image](https://github.com/InseeFrLab/onyxia/assets/48868412/d022948d-5623-4e46-9a00-5ee938d72fc2)

**Comment by garronej** [comment]
Yes, rushed release. Fixing first thing tomorrow morning. Sleeping now

**Comment by garronej** [comment]
Fixed
