### ISSUE TITLE
Vault error 400 on new group(maybe user) 

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia#735]
on last version of onyxia v8.1.7 and maybe before at creation of onyxia group (and maybe also new user not sur

GET | https://vault.url/v1/onyxia-kv/metadata/some-projet/.onyxia?list=true get a 404  that blocks all the mechanism.

**Comment by garronej** [comment]
Ahhh but it's 8.1.7
Allright, it's fixed in 8.1.8 👍🏻
