### ISSUE TITLE
Call private catalogs endpoint when user is logged in

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia#742]
Hi !  

Following the merge & release (in `v2.1.0`) of https://github.com/InseeFrLab/onyxia-api/pull/369 , we should call the `my-lab/catalogs` instead of `/public/catalogs` when user is logged in. Response model from the API is the same in both endpoints so no other change should be needed

**Comment by garronej** [comment]
Got it, will be done tomorrow

**Comment by fcomte** [comment]
I guess it's closed? @garronej

**Comment by garronej** [comment]
Sure sorry!
