### ISSUE TITLE
Service disconnected/got shut down and then dissapeared?

### ISSUE THREAD

**Issue by ItsMeVictor** [InseeFrLab/onyxia#743]
I used the "Vscode-python-gpu" service to train a machine learning model which was expected to take about 20 hours to run, and I had thus let it run in the background. 

After about five hours of runtime, I went back to the Datalab window and received an error message of the sort "Disconnected. Try to reconnect". When I clicked on the "Try reconnecting now" button, I was just instantly sent back to the "My Services" page which was, this time, empty. I have not been able to recover my service since then. 

I don't really understand what happened? The only thing to report is that I connected to a VPN and then disconnected at some point in the five-hours window, which means that my IP must have changed, but while I see why it might disconnect me, I have trouble understanding why it would plainly lead to the deletion of my instance. 

Thanks in advance for your input. Off to creating a new service in the meantime :-)

**Comment by garronej** [comment]
Hello @ItsMeVictor,  
This is the code source of the open source project.  
For issues related to the datalab (the INSEE instance of Onyxia) please reach out [on Slack](https://join.slack.com/t/3innovation/shared_invite/zt-1hnzukjcn-6biCSmVy4qvyDGwbNI~sWg) on the channel #datalab.
