### ISSUE TITLE
some special caracters like ? is not authorized in a vault secret

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia#744]
Several caracters allowed in a passowrd is not handle by onyxia.

**Comment by odysseu** [comment]
Also, `|` `#` `(` `)` `*` `;` `&` `>` and `<` are not allowed but should be

**Comment by garronej** [comment]
Thanks for reporting, Fixed and did this as well:  

https://github.com/InseeFrLab/onyxia/assets/6702424/ec8d5a73-480c-45d9-892c-b1ff8cc9d360
