### ISSUE TITLE
file browser hangs when we want to reach upper folder in the browser file

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia#745]
![image](https://github.com/InseeFrLab/onyxia/assets/63847345/334ff1bc-f0e4-4807-8a31-1a0e9ced6b84)

Here in an onyxia instance with a shared bucket for user when clicking on "<" icon the browser will bug because a 403 will be launched.

**Comment by garronej** [comment]
Fixed sorry for the delay in addressing this
