### ISSUE TITLE
Wrong link when already logged in 

### ISSUE THREAD

**Issue by ihiverlet** [InseeFrLab/onyxia#748]
When trying to connect while already connected - the "You are already logged in" window is displayed.
However the link "Back to Application" points to the current window instead of datalab.sspcloud.fr

**Comment by garronej** [comment]
Hello @ihiverlet,  

I can't reproduce but I'm very worried about what may cause this issue.  

Would you share a screen cap of what's going on?  
What browser are you on?

**Comment by ihiverlet** [comment]
Hello @garronej,

Here is what it looked like, using chrome 
Unfortunately I am not able to reproduce

![image](https://github.com/InseeFrLab/onyxia/assets/94982379/ee779757-c96e-40f7-8774-fa13e48dd1c6)
