### ISSUE TITLE
Exception when running a service without icon

### ISSUE THREAD

**Issue by nitreb** [InseeFrLab/onyxia#755]
In a Helm repository, when the `icon` field of the `Chart.yaml` file is not provided, the service will not be able to be launched on Onxyia. Also, an error appears in the console: 
> Uncaught (in promise) Error: Wrong assertion encountered

According to the Helm documentation, this field is optional, and unless I'm mistaken, I don't see it mentioned in the Onyxia documentation. 

What do you think of this behavior?

**Comment by fcomte** [comment]
clearly something to fix fast :) @garronej

**Comment by garronej** [comment]
Thank you for reporting, sorry about the error. Fixed

**Comment by nitreb** [comment]
Thank you for the reactivity!
