### ISSUE TITLE
Auto-refresh on new file upload

### ISSUE THREAD

**Issue by qgau** [InseeFrLab/onyxia#762]
The _My files_ view is not refreshed when new files are added in the background.

Some users created (and launch) services that automatically produce data and upload it into their personnal storage.
The consequence is that these users keep refreshing the _My files_ view until their data appears.

Is there a way to automatically refresh the _My files_ content?

This is a feedback coming from a hackaton that occured on our onyxia instance (along with plenty of nice comments on your work :wink: )

**Comment by fcomte** [comment]
I don't know how we can do that technically except by pulling S3 at regular interval. 
Do you have other idea?

**Comment by fcomte** [comment]
Another option is to manage a new notification service which could collect all events from all services.
for example with this configuration on minio : https://min.io/docs/minio/linux/administration/monitoring/publish-events-to-webhook.html#minio-bucket-notifications-publish-webhook 

This would be quite ambitious

**Comment by fcomte** [comment]
@garronej what do you think ?

**Comment by garronej** [comment]
@qgau Sorry it slipped through.  Thanks for reporting!  

I think this works now.
