### ISSUE TITLE
Blank view when accessing a non-existing catalog tab

### ISSUE THREAD

**Issue by qgau** [InseeFrLab/onyxia#764]
Hello,

We are playing around with hidden catalog tabs (only accessible if we know the repository names and put them in the URL), and we notice that if we misnamed a catalog tab, no error is displayed, only an almost blank view.

Example -> https://datalab.sspcloud.fr/catalog/wotwot

Displaying an error or redirect to the catalog root (in our example, https://datalab.sspcloud.fr/catalog/) could improve the UX.

**Comment by olevitt** [comment]
Hi !

Small note that may interest you : there is now support for "restricted" catalogs in that you can set restrictions (based on user attributes such as groups) on who is able to see and use a given catalog.
That may be more useful than using hidden catalogs for testing purposes.
See here : https://github.com/InseeFrLab/onyxia-api/pull/369

**Comment by fcomte** [comment]
In SSPCloud we are using both : hidden catalogs when services is started by links on external web site ( specific formation for example ) and restricted catalog ( our dev catalog for admins )

**Comment by qgau** [comment]
Hi!

That is great thanks for the tips @olevitt  and @fcomte , will definitively help our usage.

I let you close this issue if you don't think it is relevant to implement a redirection to avoid a user ending in a blank view.
It won't be a big problem in our use case anymore.

**Comment by fcomte** [comment]
@garronej what do you think ?

**Comment by garronej** [comment]
I'm not sure.  

In my understanding this falls in the realm of "undefined behavior".  

@fcomte Do you think I should adress this?  

Having a runtime exception and a pointer to the code that failed:  

![image](https://github.com/InseeFrLab/onyxia/assets/6702424/8626cf76-e19e-415e-901c-fb14eaa5dc27)


Is for me clear enough to indicate what wen't wrong.  

the catalogId does not exists. It does not match with my current view of the world. Stop.

**Comment by fcomte** [comment]
I think we can close without "solving"
