### ISSUE TITLE
Data Explorer can't read parquet file from s3

### ISSUE THREAD

**Issue by samuelfooks** [InseeFrLab/onyxia#765]
Trying to use the data explorer for a parquet file stored on an s3 bucket, version 8.4.8 of Onyxia.

https://s3.waw3-1.cloudferro.com/emodnet/geology/events_and_probabilities/submarine_landslides/EMODnet5_WP6_Sls_pt_250k_2023_nongeo.parquet

"Error: Invalid Error: NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://s3.waw3-1.cloudferro.com/emodnet/geology/events_and_probabilities/submarine_landslides/EMODnet5_WP6_Sls_pt_250k_2023_nongeo.parquet'."

But a standard query from a jupyter script locally works fine.

`import pandas as pd

parquet_url = "https://s3.waw3-1.cloudferro.com/emodnet/geology/events_and_probabilities/submarine_landslides/EMODnet5_WP6_Sls_pt_250k_2023_nongeo.parquet"

df_from_parquet = pd.read_parquet(parquet_url)

print(df_from_parquet.head(10))

   Id    Sls_pt                   Age  Volume  Thickness  \
0   0  FI100002              Holocene     0.0          4   
1   0  FI100003              Holocene     0.0          4   
2   0  FI100004              Holocene     0.0          4   
3   0  FI100005  Holocene/Pleistocene     0.0          5   
4   0  FI100006  Holocene/Pleistocene     0.0          5   
5   0  FI100007  Holocene/Pleistocene     0.0          2   
6   0  FI100008  Holocene/Pleistocene     0.0          5   
7   0  FI100009              Holocene     0.0          5   
8   0  FI100010              Holocene     0.0          1   
9   0  FI100011              Holocene     0.0          1   

`
If more info is needed let me know :) Thanks

**Comment by fcomte** [comment]
```
duckdb-browser-eh.worker-DrIFGUaA.js:1 Access to XMLHttpRequest at 'https://s3.waw3-1.cloudferro.com/emodnet/geology/events_and_probabilities/submarine_landslides/EMODnet5_WP6_Sls_pt_250k_2023_nongeo.parquet' from origin 'https://datalab.sspcloud.fr' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
There is no cors policy that allow our web app to request this bucket.
So we can't access it from our webapp

I put your file on my storage space and i can see it

![image](https://github.com/InseeFrLab/onyxia/assets/48868412/22930478-11ca-468b-a06f-6a9436365037)

**Comment by fcomte** [comment]
here is documentation for configuring cors for aws bucket : 

https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManageCorsUsing.html
