### ISSUE TITLE
The last item of service bookmark list is partially hidden when having more than 9 bookmarks

### ISSUE THREAD

**Issue by pierre-lamarche** [InseeFrLab/onyxia#767]
When having recorded more than 9 service bookmarks, the last item is hidden (still usable) by the bottom banner, as shown on this screenshot:

![image](https://github.com/InseeFrLab/onyxia/assets/19386429/251922d5-e761-4c38-b78e-2d10caf4130b)

Thanks in advance for solving this minor inconvenience.

**Comment by fcomte** [comment]
@garronej is it fixed? can we close ?

**Comment by garronej** [comment]
Yes, it's fixed.
