### ISSUE TITLE
Versioning of helm charts resulting in a warning message when launching a service through a bookmark using a outdated version of the chart

### ISSUE THREAD

**Issue by pierre-lamarche** [InseeFrLab/onyxia#768]
It looks like the different charts for launching a service are versioned, which is fine but results in being displayed a somehow disturbing message, suggesting something went wrong when deploying the service (while it did not).

Here's a screenshot that I am displayed with a bookmark concerning a RStudio service:

![image](https://github.com/InseeFrLab/onyxia/assets/19386429/68b8d48d-2120-443a-9ce3-e7c24c99e098)

The service is still launched, everything is fine, but users may be puzzled by this annoying message. It disappears when updating manually the bookmark, but the addition of some sort of automatic update or button for update would be great.
Many thanks in advance.

**Comment by avouacr** [comment]
@garronej @fcomte what are your thoughts on this? I find this message rather concerning for users, it suggests an error while in fact it is just a relatively trivial warning. I would suggest a quick fix : suppress it altogether, it is the logical behavior anyway to fall back on the latest chart.

**Comment by garronej** [comment]
Shure, I can do that

**Comment by garronej** [comment]
Done
