### ISSUE TITLE
Activating quotas after user creation raise an error when accessing "my services"

### ISSUE THREAD

**Issue by nitreb** [InseeFrLab/onyxia#769]
We have activated quotas for our project, and when a user tries to access "my services", a pop up with `TypeError: can't convert undefined to object` appears. It seems that the error is raised because there is no kubernetes `ResourceQuota` associated with the user namespace. Even though we will manually create `ResourceQuota` for each user, I feel like this must be dealt with in the frontend.

Thanks!

**Comment by fcomte** [comment]
can you show the api response for the quota request on onyxia-api ?

**Comment by nitreb** [comment]
I got an empty response but with status 200, nothing much to show...

**Comment by fcomte** [comment]
@olevitt @garronej 

so I guess onyxia-web must handle this 200 empty response?

**Comment by garronej** [comment]
I'll handle this on the application side but I think the API should respond with `{ "spec": [], "usage": [] }` instead of an empty 200.

**Comment by fcomte** [comment]
agree

**Comment by olevitt** [comment]
Done in https://github.com/InseeFrLab/onyxia-api/pull/400  
Will be in API `v2.3.0`, soon to be released

**Comment by garronej** [comment]
Cool thanks I've fixed it on my side in the meantime but I'll revert my changes
