### ISSUE TITLE
vaultToken is kept in the session storage after logout

### ISSUE THREAD

**Issue by nitreb** [InseeFrLab/onyxia#770]
The vaultToken is kept in the session storage after logout, which seems to cause issue when switching between account. If I'm on account A, logout and login with account B, the requests sent to vault end up with a 403 HTTP error, and prevent me from accessing the datalab until I manually clear it from my browser session storage.

Thanks!

**Comment by fcomte** [comment]
we should fix that asap

**Comment by garronej** [comment]
Thank you for reporting @nitreb,  

It was indeed an issue. It shoud be fixed in the latest version of Onyxia (it's being deployed)

**Comment by nitreb** [comment]
Problem is fixed, perfect, thank you!
