### ISSUE TITLE
Enhance UX regarding resources quotas

### ISSUE THREAD

**Issue by odysseu** [InseeFrLab/onyxia#772]
Hi,
It would be great to enhance the UX regarding the quota resources usage that users can see in their "My services" page.
With default settings in onyxia's values.yaml file.

- [x] Precise the threshold for :
  - [x] "warning" zone (75% by default).
  - [x] "danger" zones (95% by default).
- [ ] add a brief description button (❔) of what the resource is.
- [x] ~~precise whether the quotas informations are always displayed or not : should be a user's choice : "false" by default, "always true" or with a threshold chosen on a scale from 0% to 100% that represents the minimum of % used in any of the resource qota, located in the "My account" page.~~

**Comment by fcomte** [comment]
threshold are available on the web : 

https://github.com/InseeFrLab/onyxia/blob/e961755d83309a5f1db6ba53e3bd2cd3503afc66/web/.env#L725-L732

I agree we should configure CRITICAL zone and a brief description button is possible.

I am not sure for the last idea. It require storage on vault for very little value.

**Comment by fcomte** [comment]
can we close that ? @odysseu @garronej

**Comment by odysseu** [comment]
yes we can !
