### ISSUE TITLE
The .env file mentions CUSTOM_RESOURCES_URL and CUSTOM_RESOURCES

### ISSUE THREAD

**Issue by nitreb** [InseeFrLab/onyxia#776]
I think `CUSTOM_RESOURCES_URL` is deprecated? We manage to make it work by using `CUSTOM_RESOURCES`. Both are mentioned in the .env file and it might be confusing for the users.
What do you think?

**Comment by odysseu** [comment]
Indeed, I can also see the 2 variables appear in the code:
- [CUSTOM_RESOURCES_URL](https://github.com/search?q=repo%3AInseeFrLab%2Fonyxia%20CUSTOM_RESOURCES_URL&type=code)
- [CUSTOM_RESOURCES](https://github.com/search?q=repo%3AInseeFrLab%2Fonyxia%20CUSTOM_RESOURCES&type=code)

**Comment by garronej** [comment]
Hello @nitreb,  
Thanks for the feedback,  
The `CUSTOM_RESOURCES_URL` is not deprecated but it's an internal parameter that isn't supposed to be customized.  

<img width="698" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/086cef9f-9fc0-421f-ad44-284b3e91acb5">


Everywhere else, only `CUSTOM_RESOURCES` is mentioned. This is what needs to be used.  

I'll remove or rename  `CUSTOM_RESOURCES_URL` to clearup confustion.

**Comment by garronej** [comment]
I admit it was missleading, I found another way so that there's no need for the `CUSTOM_RESOURCES_URL` internal variable.  

Thanks for reporting
