### ISSUE TITLE
Adding GLOBAL_ALERT widens the resolution of the page

### ISSUE THREAD

**Issue by nitreb** [InseeFrLab/onyxia#777]
We added a `GLOBAL_ALERT` in our config, and a horizontal scrollbar appeared on [our datalab](https://datalab.dive.edito.eu/). Closing the alert makes it the right size again. Did you experience something similar on your side or have we put a text too big? It does it on Firefox but not Chrome.

Thank you

**Comment by odysseu** [comment]
Same experience here

**Comment by garronej** [comment]
@nitreb, @odysseu Thanks for reporting, I'll look into it shortly

**Comment by garronej** [comment]
It was suprisingly hard to fix.  

It was hapenning only on Firefox, this is why I didn't noticed it before.  

Thanks for reporting!
