### ISSUE TITLE
onyxia-api Quota notification should be more discret

### ISSUE THREAD

**Issue by odysseu** [InseeFrLab/onyxia#780]
As seen in the following screenshot, the UI interrogates the API every 30 seconds to refresh the quotas :

![The onyxia-ui interrogates the onyxia-api every 30 seconds](https://github.com/InseeFrLab/onyxia/assets/55583423/a4a9fdf4-2fbe-4838-85f1-2c124c366346)

When the internet is broken or the API is not responding, **it would be nice to have an icon that says the status is offline instead of having a big pop-up** that blinds the user's interface.
Or if the icon is not the priority, at least take off the big pop-up that we can see in the following screenshot :

![The onyxia-ui will pop-up an error when there is no connections with the onyxia-API](https://github.com/InseeFrLab/onyxia/assets/55583423/b4861bc0-ca13-44e6-adf8-ede115cce4b7)

**Comment by garronej** [comment]
@odysseu thanks for submitting the issue, it's addressed.

**Comment by garronej** [comment]
(still deploying)

**Comment by odysseu** [comment]
Hi, this is still an open issue:

![image](https://github.com/InseeFrLab/onyxia/assets/55583423/981cc207-a2ba-4a56-9a0e-a32597823fb7)

**Comment by garronej** [comment]
Yes sorry the latest build hasn't been published yet but it is indeed fixed on main.
