### ISSUE TITLE
Disabling personal data injection by default in groups impedes simple git commits

### ISSUE THREAD

**Issue by fBedecarrats** [InseeFrLab/onyxia#782]
Hi all, this group functionality is great to facilitate collaboration within teams. I however noted that git personal environment variables were not injected anymore. It implies for user to manually enter them in the pod configuration before launching, or on the terminal once the pod is launched. I understand that this is recommended when the service is shared, but I don't think that it is suitable of services are not shared (when the box below is not checked):
![image](https://github.com/InseeFrLab/onyxia/assets/3328347/434bae6a-6f17-46b3-aa37-77d6c89ccc4a)
The use case I would have for groups is to share storage, and pod configured images (including Init configurations pointing to a shared Github repo), but services are not shared, so there is no risk to compromise personal secrets and users can push git commits on their own name without further manual configuration.
I hope that I am making myself clear here. Please do not hesitate to tell me to elaborate if it seems confusing.
Thanks again!

**Comment by fcomte** [comment]
It's unsafe to start any personnal data in a shared namespace. User should start rstudio in their own namespace.

**Comment by fBedecarrats** [comment]
OK, thanks. So the use case for groups is really about sharing data (S3 or shared databases), not configurations or analytic services. Thanks for the clarification!
