### ISSUE TITLE
some documentation link are not easy to change

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia#784]
Hello

Some links are hard coded : 

https://github.com/search?q=repo%3AInseeFrLab%2Fonyxia%20docs.sspcloud.fr&type=code

We should enable admin to modify documentation link

**Comment by odysseu** [comment]
Yes, see https://github.com/search?q=repo%3AInseeFrLab%2Fonyxia%20docs.sspcloud.fr&type=code

**Comment by garronej** [comment]
Thoses links are now customizable: https://github.com/InseeFrLab/onyxia/blob/53b8e655f9427c655d61df8a7d1298f141b5e1f8/web/.env#L747-L757
