### ISSUE TITLE
Launcher service configurations tabs displayed at page opening

### ISSUE THREAD

**Issue by Eldrile** [InseeFrLab/onyxia#787]
Today the configuration tabs are closed  when arriving in the launching service page. 
We would like to be able to have this tabs opened by default, as some of our services should be modified by the user before launching them.

**Comment by garronej** [comment]
Ok, I can add a configuration parameter for this.

**Comment by garronej** [comment]
I just added a new configuration:  

https://github.com/InseeFrLab/onyxia/blob/5b17a8b925bbe414e987ce807506eea00c25811a/web/.env#L741-L745  

Best

**Comment by Eldrile** [comment]
Thanks a lot !
