### ISSUE TITLE
Saving configuration for two different services with the same name overwrites the first config.

### ISSUE THREAD

**Issue by trygu** [InseeFrLab/onyxia#789]
Not a very big issue, but some times it would be convenient to use the name of the repo I want to open automatically using the saved configuration feature. Some times I would like to open the same repo, but with different services, e.g. Jupyter AND vscode f.ex. 

Easy work-around is to prefix the names with the name of the service etc. Anyway a warning would at least be nice. :-) 

Screenshot added.
![Skjermbilde 2024-04-04 kl  22 25 52](https://github.com/InseeFrLab/onyxia/assets/3669823/89645977-2795-45e2-8481-47ad25518942)

**Comment by garronej** [comment]
Ok

**Comment by garronej** [comment]
I'll do it

**Comment by garronej** [comment]
@trygu Done!  

You can now have the different config with the same name as long as they are not for the same service.  

<img width="578" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/b8dc86df-28c5-4950-8c44-19ffa74761c7">

Thanks for reporting!
