### ISSUE TITLE
Onyxia web UI spam request token to the OIDC

### ISSUE THREAD

**Issue by AlexisGuthix** [InseeFrLab/onyxia#797]
Hi,

When we navigate through the Onyxia web UI, it sends multiple token requests to our OIDC, +50 per second. Is this behavior specific to our environment, or is it something configurable on the Onyxia side?

![onyxiarequest](https://github.com/InseeFrLab/onyxia/assets/140300089/0893f370-9e9c-451b-9f3f-4bf71c9918d6)

**Comment by garronej** [comment]
Hello @AlexisGuthix,  

This is obviously verry bad.  
Can we schedule a call so I can look into it?  

Let's talk on Slack: https://join.slack.com/t/3innovation/shared_invite/zt-1hnzukjcn-6biCSmVy4qvyDGwbNI~sWg

**Comment by AlexisGuthix** [comment]
Hey, since Cédric had dealt this directly with you, I had completely forgot about this ticket which can now be closed !

Regards,
Alexis
