### ISSUE TITLE
Data explorer - number of windows

### ISSUE THREAD

**Issue by jpramil** [InseeFrLab/onyxia#805]
Weird number of windows when exploring a .csv (bottom rigth).
Could be due to the lack of expected .parquet metadata
![image](https://github.com/InseeFrLab/onyxia/assets/100139338/6bcd0f76-edc3-4b48-bacc-b0d02e8a229b)

**Comment by garronej** [comment]
Hello @jpramil,  

Thank you for reporting!  
I just fixed it.  

https://filedn.com/lYPEPucNMheV19aDu23lK0Q/misc/Screen%20Recording%202024-05-03%20at%2019.42.20.mov
