### ISSUE TITLE
Differentiate the repository URL from the index.yaml URL in the catalogs configuration

### ISSUE THREAD

**Issue by nitreb** [InseeFrLab/onyxia#806]
Hi!

When configuring a [catalog](https://github.com/InseeFrLab/onyxia-api/blob/87655442262b38bdfbd0c1d6842a85429188ce11/onyxia-api/src/main/resources/catalogs.json), there a `location` field to set the URL of the catalog. It's used for both getting the charts index file, and build the link to the repository in the catalog page header help section in the datalab.

The issue we have is that in our case, those links are not the same. We host our charts with the package registry of Gitlab, and to access the `index.yaml` file, we need to point to an API url. Thus, we configure the `location` field to [https://gitlab.mercator-ocean.fr/api/v4/projects/1974/packages/helm/playground](https://gitlab.mercator-ocean.fr/api/v4/projects/1974/packages/helm/playground), that does not point to our [repository](https://gitlab.mercator-ocean.fr/pub/edito-infra/helm-charts/playground) directly... 

Would it be possible to differentiate the two? With maybe a `repositoryLocation` and `indexLocation` fields?

**Comment by fcomte** [comment]
do you like having that on your platform ?

![image](https://github.com/InseeFrLab/onyxia/assets/48868412/1ef1b09f-c170-4655-bcc7-a0161ab20f83)

I think we should at least give an option to remove this help because it's not really usefull for 99,9% of users.

**Comment by garronej** [comment]
Hi @nitreb,

You should be able to resolve the issue on your end.

Ensure that both `index.yaml` and `index.html` files are present in your public directory:


https://github.com/InseeFrLab/helm-charts-interactive-services/tree/gh-pages

<img width="627" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/bda31218-ca65-43ec-8b2b-2586c4942c79">

When an HTTP GET request is made to: 
https://inseefrlab.github.io/helm-charts-interactive-services  
GitHub Pages will automatically redirect to `index.html`. I believe GitLab will exhibit similar behavior.

Helm explicitly queries the `index.yaml`.

In the `index.html`, to redirect users to the repository, use the following snippet:

https://github.com/InseeFrLab/helm-charts-interactive-services/blob/42d043e49bca7c5abdc689944a75e078f635b92b/index.html#L1-L5

Replace the URL with the URL of your repository.  


@fcomte, I propose we remove the informational notice altogether as it occupies too much space and, without the link, it conveys no essential information. It might as well say, "Look! Very easy, very cool!".

How about removing the page header on the catalog page and replacing it with a command bar like this:

```bash
helm repo add ide https://inseefrlab.github.io/helm-charts-interactive-services
```
This could be updated dynamically when switching catalog tabs.  
It would provide the relevant information, occupy less space, and both users and administrators can hide the command bar if needed. What are your thoughts?

**Comment by nitreb** [comment]
Thank you both for your response! 

Unfortunately, we do not use Gitlab pages but the [package registry](https://docs.gitlab.com/ee/user/packages/helm_repository/) functionality. This mean that we access the `index.yaml` file through the Gitlab API, and not the repository URL.

Maybe a quick fix would be to add an option to remove the section completely.

**Comment by odysseu** [comment]
Same behavior as @nitreb when using gitlab package registry

**Comment by fcomte** [comment]
I agree with @garronej proposal

**Comment by nitreb** [comment]
Maybe this section can be reworked and display the description of the catalog. The description can support the markdown format. It would give the possibility to be more descriptive of each catalog purpose, and also put whatever link we want!

**Comment by garronej** [comment]
@nitreb Good idea, let's do that!

**Comment by garronej** [comment]
It's done.  
Now the catalog's description, which is a localized string is displayed in the header of the catalog page as markdown if defined.  

<img width="771" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/57e32f44-b889-41b2-b0c7-727c35b07650">

I updated the documentation: https://docs.onyxia.sh/admin-doc/catalog-of-services


<img width="835" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/d64ed8c8-6317-44e0-b62c-cd597b9660a6">


<img width="808" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/927987f6-a05c-41c0-8273-282676855e7d">

**Comment by nitreb** [comment]
Nice! Thank you @garronej

**Comment by garronej** [comment]
the api changes relative to this needs to be merged first though...

**Comment by odysseu** [comment]
I am not sure the API evolution would be enough.

Hear me out : 

![image](https://github.com/InseeFrLab/onyxia/assets/55583423/63c3644e-40c6-4f88-a563-fa33b2a7fed7)


When one uses gitlab, the "2." link sends to `https://gitlab.<domain>/api/v4/projects/<project ID>/packages/helm/stable/` which is not understood by gitlab/the navigator because it is understandable **for helm**.

**Comment by nitreb** [comment]
@odysseu I did not see this one, well spotted. Also, this link does not open in a new tab, which can be inconvenient...

**Comment by odysseu** [comment]
Must change something somewhere here : https://github.com/InseeFrLab/onyxia/blob/web-v4.27.0/web/src/ui/i18n/resources/fr.tsx#L713-L722 and there : https://github.com/InseeFrLab/onyxia/blob/web-v4.27.0/web/src/ui/pages/launcher/LauncherMainCard.tsx#L258-L264

**Comment by garronej** [comment]
Ok I've updated the logic Onyxia now performs some best effort inference for providing better insight on what the sources links points to:  

![image](https://github.com/InseeFrLab/onyxia/assets/6702424/2786ffbf-2f3d-49e7-9fa5-b32534789b56)  

The logic is here:  

https://github.com/InseeFrLab/onyxia/blob/6627e0ad4e2dae7e65fccb01cd0166769659ab6f/web/src/core/usecases/launcher/selectors/selectors.ts#L559-L627  

So basically, if you want the three link linke in the screenshot for your [vscode-python-gpu] on GitLab you would put in your `Chart.yaml`:  

```diff
 apiVersion: v2
 name: vscode-python-gpu
 description: The VSCOde IDE with Python, Julia, and a collection of standard data
   science packages, with GPU support.
 icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/vscode.png
 keywords:
 - VSCode
 - Python
 home: https://code.visualstudio.com/
 sources:
-- https://github.com/InseeFrLab/images-datascience
-- https://github.com/InseeFrLab/helm-charts-interactive-services
+- https://gitlab.mercator-ocean.fr/pub/edito-infra/helm-charts/playground/-/tree/main/vscode-python-gpu
+- https://github.com/InseeFrLab/images-datascience/tree/main/vscode
 type: application
 version: 1.11.19
 dependencies:
 - name: library-chart
   version: 1.5.17
   repository: https://inseefrlab.github.io/helm-charts-interactive-services
```  

But you don't **have** to put all thoses liks. It's just that if they are present, Onyxia will do it's best to generate insightfull helper messages by inferring where the links likely points to.

**Comment by fcomte** [comment]
Can we close this issue? @garronej @nitreb

**Comment by nitreb** [comment]
Looks good to me, thanks!
