### ISSUE TITLE
Onyxia web env variable BACKGROUND_ASSET do not hide background on terms of services page

### ISSUE THREAD

**Issue by slim0** [InseeFrLab/onyxia#810]
Hi,

We found out that setting the env variable "BACKGROUND_ASSET" to false in onyxia web do not hide the background image on the "terms and conditions" page (in onyxia keycloak theme).
It works well on the login page by the way.

Regards

**Comment by garronej** [comment]
Hum,  

I don't quite get what's going on.  

I wasn't able to reproduce unfortunately.  
Can you show me what you're getting in the localStorage?  

<img width="2048" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/79d88e0f-71d5-4f0d-bb35-8005c40ff8df">

**Comment by slim0** [comment]
My bad, this is on the next page. The one that is asking to verify the email.

![Capture d’écran 2024-05-24 à 09 03 15](https://github.com/InseeFrLab/onyxia/assets/46485341/d793691f-21c1-4a14-bbb2-1528f42f9778)

<img width="896" alt="Capture d’écran 2024-05-24 à 09 01 31" src="https://github.com/InseeFrLab/onyxia/assets/46485341/89b72438-4f93-4cdf-af9b-b03a57df101d">

**Comment by garronej** [comment]
Ok now that makes sense!

**Comment by garronej** [comment]
I foud the error. Fixing, thanks for reporting

**Comment by garronej** [comment]
Fixed in latest version!
