### ISSUE TITLE
Trying to create jupyter notebook in Vscode-python service

### ISSUE THREAD

**Issue by 2FromField** [InseeFrLab/onyxia#811]
Hello, 
I'm trying to create an .ipynb file (jupyter notebook) in a Vscode service on the Onyxia Datalab and this is what it shows me:

![Capture d'écran 2024-05-24 094615](https://github.com/InseeFrLab/onyxia/assets/115177083/56f3d577-a53c-4134-a7ce-8868f348f94d)

Do I have to use a Jupyter-python service? 
Thanks.

**Comment by olevitt** [comment]
Hello,  

This looks like a reverse proxy misconfiguration somewhere in your infrastructure to me. 
Please check your browser's logs (network and console) for more details

**Comment by 2FromField** [comment]
Here's what the logs return when the error occurs:

Error: Could not initialize webview: Error: Could not register service worker: SecurityError: Failed to register a ServiceWorker for scope ('https://project-datalab-challenge-seenovate-835005-0.lab.intra-seenovate.com/stable-9a28bc29dbddb6886dfe03dc1c31320249a901ce/static/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://project-datalab-challenge-seenovate-835005-0.lab.intra-seenovate.com/stable-9a28bc29dbddb6886dfe03dc1c31320249a901ce/static/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority=project-datalab-challenge-seenovate-835005-0.lab.intra-seenovate.com'): An SSL certificate error occurred when fetching the script..}
    at u.value (backLayerWebView.ts:576:28)
    at s.y (event.ts:1156:13)
    at s.fire (event.ts:1187:9)
    at webviewElement.ts:232:23
    at webviewElement.ts:510:35
    at Set.forEach (<anonymous>)
    at H.onmessage (webviewElement.ts:510:16)

**Comment by fcomte** [comment]
I am closing this issue as it seems to be a ssl certificate issue.
