### ISSUE TITLE
Filter probe errors from the events displayed at service creation

### ISSUE THREAD

**Issue by avouacr** [InseeFrLab/onyxia#814]
Hi @garronej,

The display of events when launching a service from the catalog is a pretty cool feature, but unfortunately it also displays irrelevant errors, particularly those from probes' healthchecks that almost systematically happen during startup. I think we should filter out these specific events, as they can mislead users into believing there is some sort of error with their service creation although it actually creates itself as expected.

![image](https://github.com/InseeFrLab/onyxia/assets/43444134/e99d4f84-ee6c-4475-9776-48058940c685)

**Comment by fcomte** [comment]
maybe we can only add an expand button to see all the details (events) when a service is starting.... most users don't want to see this meaningless event.

what do you think @avouacr ?

**Comment by avouacr** [comment]
Yes that's probably even better in terms of UX. In that case we should also put the red progress bar within the expandable component, otherwise it visually clashes a bit with the animation on the "open the service" button before it appears.

**Comment by fcomte** [comment]
yes i think also : most of the time all of this take 5 seconds. 

@garronej what do you think , can we hide that by default and let user expand to see this noisy details ?

**Comment by garronej** [comment]
I filtered out probe failed from the open modal.
