### ISSUE TITLE
Support overriding more fields with values from X-Onyxia

### ISSUE THREAD

**Issue by nicolst** [InseeFrLab/onyxia#819]
## Background

Currently we have the option to override a field's default value using `.x-onyxia.overwriteDefaultWith`:

```json
"myField": {
  "type": "string",
  "default": "",
  "x-onyxia": {
    "overwriteDefaultWith": "some.attribute"
  }
}
```

As well as an option to specify which region's config to use for slider values. This is very useful, but in some cases a bit lacking.

## Proposal

In some cases it could be useful to override/populate other properties of a field as well. For example, we would like to have a drop-down choice which is populated with a user's groups, which is included as a claim in their ID token:

```json
"group": {
  "type": "string",
  "default": "",
  "render": "list",
  "listEnum": []
}
```

In this case, we want to override both the default value (to say, the first group in the user's list of groups), and the `listEnum` property. Two examples of how this could look:

Following the current naming scheme
```json
"group": {
  "type": "string",
  "default": "",
  "render": "list",
  "listEnum": [],
  "x-onyxia": {
    "overwriteDefaultWith": "user.decodedIdToken.groups[0]",
    "overwriteListEnumWith": "user.decodedIdToken.groups"
  }
}
```

More general and extendable structure?
```json
"group": {
  "type": "string",
  "default": "",
  "render": "list",
  "listEnum": [],
  "x-onyxia": {
    "overrides": {
      "default": "user.decodedIdToken.groups[0]",
      "listEnum": "user.decodedIdToken.groups"
    }
  }
}
```

**Comment by fcomte** [comment]
I prefer to keep the same structure to avoid migration of all charts.

**Comment by garronej** [comment]
I like this proposal. It's simple enough it adresses a valid usecase and the first option is retrocompatible

**Comment by trygu** [comment]
> I like this proposal. It's simple enough it adresses a valid usecase and the first option is retrocompatible

Very nice, @garronej! 

Any idea when we could get this in Onyxia? It's a bit of a blocker for us for our grand plan on going into production this summer. <3

**Comment by garronej** [comment]
Hey @trygu,  
I'm shipping this today

**Comment by trygu** [comment]
> Hey @trygu, I'm shipping this today

Did I mention that we love you? ❤️

**Comment by garronej** [comment]
Sorry I wasn't able to do it today but tomorrow for sure!

**Comment by garronej** [comment]
It's done. Allow me a couple of hours to test hedge cases and document the feature and I'll ship

**Comment by garronej** [comment]
@nicolst @trygu It's released! :)  

https://docs.onyxia.sh/admin-doc/catalog-of-services#x-onyxia-overwritelistenumwith

**Comment by fcomte** [comment]
i reopen it as onyxia-api does not handle the new field

**Comment by garronej** [comment]
Oh gosh I forgot that the values are not forwareded as it by the API. Good catch!

**Comment by garronej** [comment]
This is released
