### ISSUE TITLE
Filter service catalog

### ISSUE THREAD

**Issue by 2FromField** [InseeFrLab/onyxia#824]
Hello, 
Is it possible to filter the services offered in the "**service catalog**"? For example, display only "Jupyter-python" and not "Jupyter-python-gpu" and others? 
Thank you.

**Comment by garronej** [comment]
Hello @2FromField,  
Not yet but we can figure something out

**Comment by fcomte** [comment]
It's already available 

```
        {
          "id": "inseefrlab-helm-charts-datascience",
          "name": "Deprecated",
          "maintainer": "innovation@insee.fr",
          "location": "https://inseefrlab.github.io/helm-charts-datascience",
          "status": "PROD",
          "excludedCharts":
            [
              "rstudio",
              "jupyter",
              "vscode",
              "lakefs",
              "jena",
              "mariadb",
              "spark-history",
              "dask",
              "label-studio",
              "spark-thrift-server",
              "postgresql",
              "elastic",
              "mongodb",
              "argo-cd",
              "argo-workflows",
              "hive-metastore",
              "mlflow",
              "postgresql",
              "kafka",
              "neo4j",
              "nocodb",
              "pgadmin",
              "superset",
              "pinot",
              "trino",
              "tensorflow",
              "redash",
              "delta-sharing-server",
              "openrefine",
            ],
          "type": "helm",
          "multipleServicesMode" : "maxNumber",
          "maxNumberOfVersions" : 2
```

excludedCharts list do exactly what you want

**Comment by fcomte** [comment]
already available but it's not enough documented

**Comment by garronej** [comment]
It's currently an undocumented featue, I reopen until we document it here: https://docs.onyxia.sh/admin-doc/catalog-of-services#using-your-own-catalogs-helm-charts-repositories

**Comment by 2FromField** [comment]
Great! Exactly what I was looking for, thanks for your feedback!

**Comment by fcomte** [comment]
documentation done

**Comment by 2FromField** [comment]
However, the method requires a "public" git repository to be used for the `location` parameter. Is it possible to do this for a "private" repository? A potential "token" parameter or within the url (location)?

**Comment by fcomte** [comment]
@olevitt If I remember correctly you already think about this subject

**Comment by olevitt** [comment]
There is this experiment that I had done few months ago for someone that wanted to use private helm repo : https://github.com/InseeFrLab/onyxia-api/pull/355  
But we never merged it as private helm repo is not really something properly specified and supported.
@2FromField do you really need private helm repo ? What's the need ?

**Comment by 2FromField** [comment]
The need is not such that the option of using a public repo is unthinkable, but I wanted to know if it was possible to do it with a private repo. 
If not, I'll use a public repo.
