### ISSUE TITLE
Cannot choose the desired ingress path to redirect to when clicking on the "Open the service" button

### ISSUE THREAD

**Issue by slim0** [InseeFrLab/onyxia#825]
Currently, the onyxia-api is returning all the ingresses' URL paths and the onyxia-ui is sorted them by alphabetic order. 
Then the first one is selected as being the one to open when clicking on the "Open the service" button (after a service has been launched).

It would be great to find a way to select the desired ingress rule we want to open when clicking on that button.

Please let us know what you think about that.

**Comment by fcomte** [comment]
What would be the experience ?

**Comment by fcomte** [comment]
It seem to me complexe to offer a better experience than today.
Giving contextual usage of thoses links in the Note.txt (under the control of the chart owner ) is standard. 

Having a default main URL seem also important ( and yes we don't have any other idea than this poor logic )
If you have another ideas to manage this lack of metadata , tell me

**Comment by garronej** [comment]
> sorted them by alphabetic order  

Damn it, we got exposed

**Comment by slim0** [comment]
> Having a default main URL seem also important ( and yes we don't have any other idea than this poor logic ) If you have another ideas to manage this lack of metadata , tell me

I didn't have ideas actually ^^

**Comment by fcomte** [comment]
we have already think of managing a json format inside note.txt to let chart owner specify more metadata but it's not standard.. so we finally decided to let it simple like today.

**Comment by fcomte** [comment]
@slim0 I am closing this. Feel free to re-open it when someone have an idea how to handle thoses links differently than today
