### ISSUE TITLE
Check schema or values for the presence of the project password

### ISSUE THREAD

**Issue by ludovicm67** [InseeFrLab/onyxia#838]
Right now, it seems that in order to get the "copy password" button in the dialog before opening the service, the password should be printed in the `NOTES.txt` from the chart.

Some tools might log the output of the `NOTES.txt` file, and storing passwords in the logs might not be optimal in that regard.

Instead of checking if `NOTES.txt` contains the project password, the following approaches could be also considered:

- check for `{{project.password}}` in the JSON schema
- check for the project password in the generated values file

Is it something that could be implemented?

**Comment by fcomte** [comment]
I think we will implement the second one , also with any attribute named password in case the user change the password from the default one.

It will be done fast by @garronej 

The first one would need a storage mecanism.

**Comment by garronej** [comment]
@ludovicm67 Thanks for the suggestion!  

I've released a new version the new algo is:  

- If there is the value of `project.password` in the NOTES.txt, we use it.  
- if there is a portion of the NOTES.txt matching `/password: ?([^\n ]+)/i` we use the matched password.  
- If there is the current value of `project.password` in the Helm Values of the deployment, we use it.  
- If there is a Helm Value of the deployment that has a property name `password` we use it's value.  

I hope it fits your needs.

**Comment by ludovicm67** [comment]
Thanks a lot @garronej for the update! 👍
