### ISSUE TITLE
Feature request: Option to helper text that displays "allowed email domain" in the onyxia theme

### ISSUE THREAD

**Issue by slim0** [InseeFrLab/onyxia#839]
Hello,

We thought that it would be great to have the possibility to disable (or customize) this helper text (confidentiality/RGPD reasons) via onyxia configuration.

Let us know.
Thank you.

**Comment by garronej** [comment]
Sure I can do that, what do you have in mind exactly?

**Comment by slim0** [comment]
Nothing fancy.
Maybe just an environment variable like "ONYXIA_REGISTRATION_EMAIL_HELPER_TEXT" to override the default message and that accept localized string.

**Comment by garronej** [comment]
Ok, I'll ship something like this today

**Comment by garronej** [comment]
Here you go:  

https://github.com/InseeFrLab/onyxia/blob/abf27d7e75281189a4f46c638dce0ce0ed5848ae/web/.env#L557-L579  

Thank you for the feature request.
