### ISSUE TITLE
onyxia ui don't show RAM quota

### ISSUE THREAD

**Issue by titigmr** [InseeFrLab/onyxia#841]
When we configure quota in region parameters on onyxia api, onyxia ui don't show memory quota.

The configuration:

```json
  "quotas": {
    "userEnabled": true,
    "groupEnabled": false,
    "allowUserModification": false,
    "user": {
      "count/pods": 100,
      "requests.memory": "32Gi",
      "requests.cpu": 16,
      "limits.memory": "32Gi",
      "limits.cpu": 16,
      "requests.storage": "500Gi"
      }
  }
 ```

Check quota on namespace 

 ```bash
 $ kubectl get quota
NAME           AGE   REQUEST
LIMIT
onyxia-quota   3d    count/pods: 4/100, requests.cpu: 800m/16, requests.memory: 2G/32Gi, requests.storage: 78Gi/500Gi   limits.cpu: 8/16, limits.memory: 16G/32Gi
```

On the ui:

![image](https://github.com/user-attachments/assets/3b916fa0-34b6-45e9-bf9c-68512b412117)

**Comment by garronej** [comment]
Thank you for reporing.  

@olevitt @fcomte, the API does not give this info to onyxia web:  

<img width="627" alt="image" src="https://github.com/user-attachments/assets/064e7845-f16d-45b1-b03e-9296e482bdc6">

**Comment by titigmr** [comment]
In my instance, the api return this:

![attatchment CRKKPo](https://github.com/user-attachments/assets/8bbe722d-bf58-4359-9adc-8c95118f560c)

the console raise:

![image](https://github.com/user-attachments/assets/0c6a7895-9453-4e4b-b538-00bdb7f6104a)

**Comment by garronej** [comment]
Hum ok thank you, I can probably fix that then!

**Comment by garronej** [comment]
It's fixed, thanks a lot for reporting!
