### ISSUE TITLE
openshiftSCC property mismatch between front and api 

### ISSUE THREAD

**Issue by titigmr** [InseeFrLab/onyxia#845]
The openshiftSCC injection is configured under `services` in api, however in the [front is in global region](https://github.com/InseeFrLab/onyxia/blob/4e39504e415c5ba99a9cfdd61983a285f7b9ce93/web/src/core/adapters/onyxiaApi/default/default.ts#L259)

When we define the config openshift in region, the injection not work.

The current code is:

```js 
                },
                        "openshiftSCC":
                            apiRegion.openshiftSCC === undefined
                                ? undefined
                                : {
                                      "scc": apiRegion.openshiftSCC.scc,
                                      "enabled": apiRegion.openshiftSCC.enabled
                                  }
                    })
```
I think this changes fix the issue:

```js
                },
                        "openshiftSCC":
                            apiRegion.services.openshiftSCC === undefined
                                ? undefined
                                : {
                                      "scc": apiRegion.services.openshiftSCC.scc,
                                      "enabled": apiRegion.services.openshiftSCC.enabled
                                  }
                    })
```

**Comment by garronej** [comment]
Hello @titigmr,  

Sorry for the mistake and thanks you for reporting the issue.  

I've just released a new version with the fix. It should be available to use in about 15 minutes.  

Best
