### ISSUE TITLE
configure reminder time to delete services

### ISSUE THREAD

**Issue by titigmr** [InseeFrLab/onyxia#846]
Its possible to configure the time of the reminder to delete a service, for example in an env var? 

On the [code](https://github.com/InseeFrLab/onyxia/blob/11273428dbd2fab733167816472de6342925c812/web/src/ui/pages/myServices/MyServicesCards/MyServicesCard/MyServicesCard.tsx#L26) is:

```ts
const runningTimeThreshold = 7 * 24 * 3600 * 1000;
```

Thanks you

**Comment by garronej** [comment]
Hello @titigmr,  

Yes, ok, I can make this customizable.
