### ISSUE TITLE
Force login before accessing Onyxia dashboard

### ISSUE THREAD

**Issue by mickaelbaron** [InseeFrLab/onyxia#862]
Hi,

We would like to force the user to log in on the first screen. Therefore, the Onyxia dashboard (catalog list) should not be accessible in read mode. The user must log in before being able to view the dashboard.

If the OpenID token is missing, redirect to the authentication page.

Do you think it would be an interesting feature?

Mickael

**Comment by garronej** [comment]
This is something that I can implement as an option very easyly yes as we own the oidc stack.  
I have an option for this in oidc-spa: https://docs.oidc-spa.dev/documentation/globally-enforce-authentication  

I can add an option `AUTH_GLOBALLY_REQUIRED=true|false` in the onyxia-web envs.  

@fcomte  what do you think?

**Comment by fcomte** [comment]
I am ok

**Comment by mickaelbaron** [comment]
Super, thx

**Comment by garronej** [comment]
It's implemented in the last Onyxia release: [AUTHENTICATION_GLOBALLY_REQUIRED=false](https://github.com/InseeFrLab/onyxia/blob/21ab8725591eed81d54de7e2c15c4c771572d3f7/web/.env#L756)
