### ISSUE TITLE
bash-git-prompt usage

### ISSUE THREAD

**Issue by p1r4t3-s4il0r** [InseeFrLab/onyxia#869]
Hello, 

I would like to use bash git prompt. But I can't get it working.

I have done the following :

Download bash-git-prompt repo

```bash
git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1
```

And then add this to my bashrc 

```bash
if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    source "$HOME/.bash-git-prompt/gitprompt.sh"
fi
```

Howerver, it's not working. 

I also tried the same but from the init script, no more luck.

I have done the same on an other pod, not created with onyxia, it's working perfectly. 

Is there something I'm missing ?

Thanks.

**Comment by olevitt** [comment]
Hi !  

This issue probably has more to do with the specific image / service / chart / catalog you are using than with Onyxia itself.  
Can you tell us more on what is happening ?   
* Which service are you using (vscode-python ?)  
* On which instance of Onyxia ?
* What do you mean by "it's not working" ?

Note that most services (vscode, jupyter, rstudio) uses a built-in terminal pre-configured and you may have to toy with that configuration if you want to extend the terminal capabilities. And I'm not sure how much you can do such configuration

**Comment by p1r4t3-s4il0r** [comment]
Thanks for your reply !

- I'm using a vscode-python image, version 1.11.42.
- It's a local instance of Onyxia, airgap

The [bash-git-prompt](https://github.com/magicmonty/bash-git-prompt). Show some information about your current git status inside of your terminal, it can, for example show the branch name, number of conflict, files to commit etc...

However, on the pod created with onyxia, nothing is shown. 

The expected result is like this one :

```bash
✔ ~/.bash-git-prompt [master|✔] 
16:32 $
```

I know that might have stuff to change but I don't know where to start...

**Comment by olevitt** [comment]
I got it working on a vscode in our SSPCloud instance.  
Not sure what is not working for you, I did exactly as you did :  
`git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1`      
then 
```
if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    source "$HOME/.bash-git-prompt/gitprompt.sh"
fi
```
in `~/.bashrc` and then  
`source ~/.bashrc` to make sure it's properly loaded.  
Then I had it working simply by `cd` to a git repository (cd `~/.bash-git-prompt`). It showed up as expected :  
```
(base) onyxia@vscode-python-186689-0:~/work$ cd ~/.bash-git-prompt/
(base) ✔ ~/.bash-git-prompt [master|✔] 
```  

Can you elaborate on what error you have / what is not working for you ?  

May or may not be related : https://stackoverflow.com/a/55965399

**Comment by p1r4t3-s4il0r** [comment]
Well, I don't understand why.

I tried it again and it's working perfectly.

Thanks for your time !
