### ISSUE TITLE
helm values notes not working in v10

### ISSUE THREAD

**Issue by titigmr** [InseeFrLab/onyxia#875]
Hello,

When we click on a services and want to retrieve the helm notes, an error ocurred in v10.

![image](https://github.com/user-attachments/assets/7605ddba-d39f-4673-8cd8-7ed3e3fb9790)

In the nav console i see that:

![image](https://github.com/user-attachments/assets/02302448-3e08-4628-a263-4323d9226917)

Thanks!

**Comment by garronej** [comment]
Thank you for reporting!

**Comment by garronej** [comment]
Fixed
