### ISSUE TITLE
Respect 'title' field when rendering object properties from json schema in helm charts

### ISSUE THREAD

**Issue by skykanin** [InseeFrLab/onyxia#878]
Currently object property names are rendered in the onyxia UI by [capitalizing the json key](https://github.com/InseeFrLab/onyxia/blob/f53508881f256b4bc551e2ed883d439758447eda/web/src/ui/pages/launcher/RootFormComponent/Accordion.tsx#L136-L142). Instead read the corresponding 'title' field the same way it is done when rendering other data types in the form.

So a property like this in `values.schema.json`:
```
...
"sourceData": {
  "title": "Kildedata",
  "description": "Tilgang som data-admins krever begrunnelse og lengde på varighet",
  "type": "object",
  "properties": ...
}
```
should instead render with the name "Kildedata" and not "SourceData".
![image](https://github.com/user-attachments/assets/716b7869-65b4-4b45-8370-29da5dd8af73)

**Comment by ddecrulle** [comment]
Hello,

The screenshot you provided suggests that you might not be using the latest version of Onyxia. It seems that the most recent versions do support rendering the “title” property.

Let me know if you need further assistance!

**Comment by skykanin** [comment]
We're running version `10.1.9` of onyxia and the offending code I linked is taken from the main branch of the onyxia github repository so I would assume this behaviour is included in the latest version.

**Comment by ddecrulle** [comment]
Really sorry, I overinterpreted. I’ve made the fix and am waiting for @garronej  feedback. Thank you for the report!

**Comment by garronej** [comment]
Hello @skykanin thanks for reporting and @ddecrulle thanks for taking this so quickly.

**Comment by skykanin** [comment]
AFAICT the fix in https://github.com/InseeFrLab/onyxia/commit/4bd9b0a02f947fa96d7b60e9913c6f5177459d5f only applies to root settings elements, but the 'title' field in non-root object properties should be respected too.

In the example below the root `"resources"` title is now rendered correctly as `"Ressurser"`, but  title field `"Forespørsel"` of the non-root property `"requests"` is ignored and is still rendered by capitalizing the json key `"requests"`.

This was tested on `tag: web-v4.34.14, tag: v10.1.13` of onyxia-web.

![image](https://github.com/user-attachments/assets/806ca76a-a9a3-4b7d-98a8-6467e7d90b6d)


```json
{
   "resouces": {
      "title": "Ressurser",
      "description": "Velg minimum mengde RAM og CPU som skal være tilgjengelig i tjenesten.",
      "type": "object",
      "properties": {
         "requests": {
            "title": "Forespørsel", // This is not used during rendering
            "description": "Velg mengden CPU-ressurser i millicores (M)",
            "type": "object",
            "properties": {
               "cpu": {...},
               "memory": {...}
               }
            }
         }
      }
}
```

**Comment by garronej** [comment]
Hello @skykanin it should be fixed for good now.  
Thank you for reporting!
