### ISSUE TITLE
New feature : webhook event when user log in

### ISSUE THREAD

**Issue by Yuwei0021** [InseeFrLab/onyxia#880]
Hello, 

With Onyxia, I would like to ensure that when a user logs in, it triggers some code to create the namespace for the user, specifically to avoid granting the onyxia service account the right to create/modify namespaces.

Based on my observations, when a user logs in, the onboarding endpoint of the Onyxia API is called to create or update user's namespace.
Would it be possible to emit an event when a user logs in and delay the creation/update of the namespace, so that I have the time to create the namespace instead of the Onyxia API before the onboarding process ?

Best regards,
Yuwei

**Comment by olevitt** [comment]
This is a duplicate of https://github.com/InseeFrLab/onyxia-api/issues/518  
I moved it to `onyxia-api` because it may be more relevant there

**Comment by johnksv** [comment]
@olevitt , should this issue then be closed?
