### ISSUE TITLE
onyxia v10 "offline" the visualization of  parquet file's is not working

### ISSUE THREAD

**Issue by JackLemaitre** [InseeFrLab/onyxia#899]
in v10 onyxia it seems that the parquet file vizualisation use an extension off duckdb. so offline it is leading to:
```
Error: Extension Autoloading Error: An error occurred while trying to automatically install the required extension 'parquet': Extension https://extensions.duckdb.org/v1.1.1/wasm_eh/parquet.duckdb_extension.wasm is not available
```
maybe change the way the vizualiser works or add the package duckdb  to onyxia. 

it works with csv file ( because not using duckdb i guess )

**Comment by garronej** [comment]
Hello @JackLemaitre,  

Thank you for reporting.  

It's fixed with https://github.com/InseeFrLab/onyxia/commit/93a09e3c9369208012622f3a08db4d50e8ab89e2  

A new version have been released with the patch.
